# NumPy Cheat Sheet

Quick reference for all essential NumPy methods.

In [2]:
import numpy as np

---
## 1. Array Creation

In [3]:
np.array([1, 2, 3])              # From list
np.zeros((3, 4))                 # All zeros
np.ones((3, 4))                  # All ones
np.empty((3, 4))                 # Uninitialized
np.full((3, 4), 7)               # Fill with value
np.eye(3)                        # Identity matrix
np.arange(0, 10, 2)              # Range with step
np.linspace(0, 1, 5)             # N evenly spaced
np.random.rand(3, 4)             # Uniform [0, 1)
np.random.randn(3, 4)            # Normal (0, 1)
np.random.randint(0, 10, (3,4))  # Random integers

array([[0, 5, 2, 8],
       [7, 7, 9, 3],
       [4, 2, 3, 4]], dtype=int32)

---
## 2. Array Attributes

In [4]:
arr = np.arange(12).reshape(3, 4)

print(f"shape: {arr.shape}")         # (3, 4)
print(f"ndim: {arr.ndim}")           # 2
print(f"size: {arr.size}")           # 12
print(f"dtype: {arr.dtype}")         # int64
print(f"itemsize: {arr.itemsize}")   # 8 bytes
print(f"nbytes: {arr.nbytes}")       # 96

shape: (3, 4)
ndim: 2
size: 12
dtype: int64
itemsize: 8
nbytes: 96


---
## 3. Reshaping

In [5]:
arr = np.arange(12)

arr.reshape(3, 4)        # New shape (view)
arr.reshape(-1, 4)       # Auto-calculate dimension
arr.flatten()            # 1D copy
arr.ravel()              # 1D view

# Add dimensions
arr[:, np.newaxis]       # (12,) -> (12, 1)
np.expand_dims(arr, 0)   # (12,) -> (1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

---
## 4. Indexing & Slicing

In [6]:
arr = np.arange(20).reshape(4, 5)

# Basic
arr[0]           # First row
arr[-1]          # Last row
arr[1:3]         # Rows 1-2
arr[::2]         # Every 2nd row
arr[::-1]        # Reverse rows

# 2D
arr[1, 2]        # Element at (1,2)
arr[:, 0]        # First column
arr[1:3, 2:4]    # Subarray

# Boolean
arr[arr > 10]    # Elements > 10

# Fancy
arr[[0, 2, 3]]   # Rows 0, 2, 3

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

---
## 5. Stacking & Splitting

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking
np.vstack([a, b])             # Vertical (4, 2)
np.hstack([a, b])             # Horizontal (2, 4)
np.concatenate([a, b], axis=0)  # Along axis

# Splitting
np.split(np.arange(9), 3)     # Into 3 equal
np.vsplit(a, 2)               # Split rows
np.hsplit(a, 2)               # Split columns

[array([[1],
        [3]]),
 array([[2],
        [4]])]

---
## 6. Math Operations

In [8]:
arr = np.array([1, 4, 9, 16, 25])

# Element-wise
arr + 10              # Add scalar
arr * 2               # Multiply
arr ** 0.5            # Power
np.sqrt(arr)          # Square root
np.exp(arr)           # e^x
np.log(arr)           # Natural log
np.sin(arr)           # Trig

# Aggregations
arr.sum()             # 55
arr.mean()            # 11.0
arr.std()             # Standard dev
arr.min(), arr.max()  # Extremes
arr.argmin()          # Index of min
np.cumsum(arr)        # Cumulative sum

array([ 1,  5, 14, 30, 55])

---
## 7. Axis Operations

In [9]:
arr = np.arange(12).reshape(3, 4)
print(f"Array:\n{arr}\n")

print(f"sum():       {arr.sum()}")          # All
print(f"sum(axis=0): {arr.sum(axis=0)}")    # Column sums
print(f"sum(axis=1): {arr.sum(axis=1)}")    # Row sums

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sum():       66
sum(axis=0): [12 15 18 21]
sum(axis=1): [ 6 22 38]


---
## 8. Linear Algebra

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.dot(A, B)          # Dot product
A @ B                 # Matrix multiply
A.T                   # Transpose

np.linalg.inv(A)      # Inverse
np.linalg.det(A)      # Determinant
np.linalg.eig(A)      # Eigenvalues
np.linalg.norm(A)     # Norm

# Solve Ax = b
b = np.array([5, 11])
x = np.linalg.solve(A, b)

---
## 9. Comparison & Logic

In [11]:
arr = np.array([1, 5, 3, 8, 2])

arr > 3               # [False, True, False, True, False]
np.where(arr > 3)     # Indices: (array([1, 3]),)
np.where(arr > 3, arr, 0)  # Replace with 0 where False

np.any(arr > 5)       # True (any > 5?)
np.all(arr > 0)       # True (all > 0?)

np.isin(arr, [1, 2])  # [True, False, False, False, True]
np.unique(arr)        # Unique values

array([1, 2, 3, 5, 8])

---
## 10. Sorting

In [12]:
arr = np.array([3, 1, 4, 1, 5, 9, 2])

np.sort(arr)          # Sorted copy
np.argsort(arr)       # Indices that would sort
np.sort(arr)[::-1]    # Descending

# 2D
arr2d = np.array([[3, 1], [4, 2]])
np.sort(arr2d, axis=0)  # Sort each column
np.sort(arr2d, axis=1)  # Sort each row

array([[1, 3],
       [2, 4]])

---
## 11. Broadcasting Rules

In [13]:
# Rules: Compare dimensions right-to-left
# Compatible if: equal OR one is 1

a = np.ones((3, 4))    # Shape (3, 4)
b = np.array([1, 2, 3, 4])  # Shape (4,)

# (3, 4) + (4,) -> broadcasts (4,) to (1, 4) -> (3, 4)
print((a + b).shape)   # (3, 4)

# Examples:
# (3, 4) + (4,)   -> (3, 4)  OK
# (3, 4) + (3, 1) -> (3, 4)  OK
# (3, 4) + (3,)   -> ERROR   (4 != 3)

(3, 4)


---
## 12. Random Numbers

In [14]:
np.random.seed(42)            # Reproducibility

np.random.rand(3, 4)          # Uniform [0, 1)
np.random.randn(3, 4)         # Normal (0, 1)
np.random.randint(0, 10, 5)   # Random integers
np.random.choice([1,2,3], 2)  # Random sample

arr = np.arange(10)
np.random.shuffle(arr)        # Shuffle in-place
np.random.permutation(10)     # Shuffled copy

array([0, 5, 2, 6, 3, 7, 4, 1, 8, 9], dtype=int32)

---
## 13. File I/O

In [15]:
arr = np.arange(10)

# Binary (.npy)
np.save('array.npy', arr)
loaded = np.load('array.npy')

# Multiple arrays (.npz)
np.savez('arrays.npz', a=arr, b=arr*2)
data = np.load('arrays.npz')
print(data['a'], data['b'])

# Text/CSV
np.savetxt('array.csv', arr.reshape(2,5), delimiter=',')
loaded = np.loadtxt('array.csv', delimiter=',')

[0 1 2 3 4 5 6 7 8 9] [ 0  2  4  6  8 10 12 14 16 18]


---
## 14. Views vs Copies

In [16]:
arr = np.arange(10)

# VIEWS (share memory, changes affect original)
view1 = arr[2:5]          # Slicing
view2 = arr.reshape(2, 5) # Reshape
view3 = arr.T             # Transpose

# COPIES (independent)
copy1 = arr[[1, 3, 5]]    # Fancy indexing
copy2 = arr[arr > 5]      # Boolean indexing
copy3 = arr.flatten()     # Always copy
copy4 = arr.copy()        # Explicit

# Check
print(f"Shares memory: {np.shares_memory(arr, view1)}")

Shares memory: True


---
## 15. Common Patterns

In [17]:
# Normalize to 0-1
(arr - arr.min()) / (arr.max() - arr.min())

# Standardize (mean=0, std=1)
(arr - arr.mean()) / arr.std()

# One-hot encoding
labels = np.array([0, 2, 1])
np.eye(3)[labels]

# Moving average
k = 3
np.convolve(arr, np.ones(k)/k, 'valid')

# Clip values
np.clip(arr, 2, 8)  # Min 2, max 8

# Replace NaN
arr_with_nan = np.array([1, np.nan, 3])
arr_with_nan[np.isnan(arr_with_nan)] = 0

---
## 16. Performance Tips

In [ ]:
# DO: Vectorize
result = arr * 2          # Fast

# DON'T: Loop
# result = [x*2 for x in arr]  # Slow

# DO: Preallocate
result = np.empty(1000)

# DON'T: Append in loop
# result = np.append(result, x)  # O(n^2)!

# DO: In-place operations
arr *= 2                   # No new allocation
np.add(a, b, out=result)   # Reuse array

# DO: Use specialized functions
np.dot(a, b)              # Not: (a * b).sum()

---
## Quick Reference Table

In [ ]:
reference = """
| Task                | Code                              |
|---------------------|-----------------------------------|
| Create zeros        | np.zeros((3, 4))                  |
| Create range        | np.arange(0, 10, 2)               |
| Reshape             | arr.reshape(3, 4)                 |
| Transpose           | arr.T                             |
| Sum all             | arr.sum()                         |
| Sum by axis         | arr.sum(axis=0)                   |
| Mean                | arr.mean()                        |
| Max/Min             | arr.max(), arr.min()              |
| Index of max        | arr.argmax()                      |
| Sort                | np.sort(arr)                      |
| Unique              | np.unique(arr)                    |
| Condition           | np.where(arr > 5, a, b)           |
| Matrix multiply     | A @ B or np.dot(A, B)             |
| Inverse             | np.linalg.inv(A)                  |
| Stack vertical      | np.vstack([a, b])                 |
| Stack horizontal    | np.hstack([a, b])                 |
| Save binary         | np.save('f.npy', arr)             |
| Load binary         | np.load('f.npy')                  |
| Save text           | np.savetxt('f.csv', arr)          |
| Load text           | np.loadtxt('f.csv')               |
"""
print(reference)

---
## Cleanup

In [ ]:
import os
for f in ['array.npy', 'arrays.npz', 'array.csv']:
    if os.path.exists(f):
        os.remove(f)