# Linear Algebra Operations

**Module 03 | Notebook 03**

---

## Objective
By the end of this notebook, you will master:
- Matrix and vector operations
- Dot products and matrix multiplication
- Matrix decompositions (SVD, eigendecomposition, QR)
- Solving linear systems
- Norms and determinants

In [2]:
import numpy as np
from numpy import linalg as LA
np.set_printoptions(precision=3, suppress=True)

---
## 1. Dot Product and Matrix Multiplication

In [3]:
# Vector dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Three equivalent ways
print(f"np.dot(a, b): {np.dot(a, b)}")
print(f"a @ b: {a @ b}")
print(f"a.dot(b): {a.dot(b)}")
print(f"Sum of products: {np.sum(a * b)}")

np.dot(a, b): 32
a @ b: 32
a.dot(b): 32
Sum of products: 32


In [4]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A:\n{A}")
print(f"B:\n{B}")

# Matrix multiplication (NOT element-wise!)
C = A @ B  # or np.dot(A, B) or np.matmul(A, B)
print(f"A @ B:\n{C}")

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A @ B:
[[19 22]
 [43 50]]


In [5]:
# Element-wise vs matrix multiplication
print(f"Element-wise (A * B):\n{A * B}")
print(f"Matrix multiply (A @ B):\n{A @ B}")

Element-wise (A * B):
[[ 5 12]
 [21 32]]
Matrix multiply (A @ B):
[[19 22]
 [43 50]]


In [6]:
# Matrix-vector multiplication
A = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 2, 3])

result = A @ v
print(f"A (2x3):\n{A}")
print(f"v (3,): {v}")
print(f"A @ v: {result}")  # Shape: (2,)

A (2x3):
[[1 2 3]
 [4 5 6]]
v (3,): [1 2 3]
A @ v: [14 32]


In [7]:
# Inner and outer products
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Inner product (same as dot for 1D)
inner = np.inner(a, b)
print(f"Inner product: {inner}")

# Outer product
outer = np.outer(a, b)
print(f"Outer product:\n{outer}")

Inner product: 32
Outer product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


---
## 2. Matrix Properties

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print(f"Matrix A:\n{A}")

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [9]:
# Transpose
print(f"Transpose:\n{A.T}")

Transpose:
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]


In [10]:
# Determinant
det = LA.det(A)
print(f"Determinant: {det}")

Determinant: -2.9999999999999996


In [11]:
# Trace (sum of diagonal)
trace = np.trace(A)
print(f"Trace: {trace}")
print(f"Manual: {np.sum(np.diag(A))}")

Trace: 16
Manual: 16


In [12]:
# Rank
rank = LA.matrix_rank(A)
print(f"Rank: {rank}")

Rank: 3


In [13]:
# Inverse
A_inv = LA.inv(A)
print(f"Inverse:\n{A_inv}")

# Verify: A @ A_inv = I
print(f"A @ A_inv:\n{A @ A_inv}")

Inverse:
[[-0.667 -1.333  1.   ]
 [-0.667  3.667 -2.   ]
 [ 1.    -2.     1.   ]]
A @ A_inv:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Pseudo-inverse (works for non-square and singular matrices)
B = np.array([[1, 2], [3, 4], [5, 6]])
B_pinv = LA.pinv(B)
print(f"B (3x2):\n{B}")
print(f"Pseudo-inverse (2x3):\n{B_pinv}")

B (3x2):
[[1 2]
 [3 4]
 [5 6]]
Pseudo-inverse (2x3):
[[-1.333 -0.333  0.667]
 [ 1.083  0.333 -0.417]]


---
## 3. Norms

In [15]:
v = np.array([3, 4])
print(f"Vector: {v}")

Vector: [3 4]


In [16]:
# Vector norms
print(f"L2 norm (Euclidean): {LA.norm(v)}")
print(f"L1 norm (Manhattan): {LA.norm(v, ord=1)}")
print(f"L-inf norm (Max): {LA.norm(v, ord=np.inf)}")

L2 norm (Euclidean): 5.0
L1 norm (Manhattan): 7.0
L-inf norm (Max): 4.0


In [17]:
# Manual L2 norm
l2_manual = np.sqrt(np.sum(v ** 2))
print(f"Manual L2: {l2_manual}")

Manual L2: 5.0


In [18]:
# Matrix norms
A = np.array([[1, 2], [3, 4]])

print(f"Frobenius norm: {LA.norm(A, 'fro')}")
print(f"Spectral norm (largest singular value): {LA.norm(A, ord=2)}")

Frobenius norm: 5.477225575051661
Spectral norm (largest singular value): 5.464985704219043


In [19]:
# Normalize vector to unit length
v = np.array([3, 4, 0])
v_normalized = v / LA.norm(v)
print(f"Original: {v}")
print(f"Normalized: {v_normalized}")
print(f"Norm of normalized: {LA.norm(v_normalized)}")

Original: [3 4 0]
Normalized: [0.6 0.8 0. ]
Norm of normalized: 1.0


---
## 4. Solving Linear Systems

In [20]:
# Solve Ax = b
# System:
# 2x + 3y = 8
# 4x + 5y = 14

A = np.array([[2, 3], [4, 5]])
b = np.array([8, 14])

x = LA.solve(A, b)
print(f"Solution x: {x}")

# Verify
print(f"A @ x: {A @ x}")
print(f"b: {b}")

Solution x: [1. 2.]
A @ x: [ 8. 14.]
b: [ 8 14]


In [21]:
# Alternative: using inverse (less stable, slower)
x_inv = LA.inv(A) @ b
print(f"Using inverse: {x_inv}")

Using inverse: [1. 2.]


In [22]:
# Least squares solution (overdetermined system)
# More equations than unknowns
A = np.array([[1, 1], [1, 2], [1, 3]])
b = np.array([1, 2, 2])

# lstsq returns: solution, residuals, rank, singular values
x, residuals, rank, s = LA.lstsq(A, b, rcond=None)
print(f"Least squares solution: {x}")
print(f"Residuals: {residuals}")

Least squares solution: [0.667 0.5  ]
Residuals: [0.167]


---
## 5. Eigenvalues and Eigenvectors

In [23]:
A = np.array([[4, -2], [1, 1]])
print(f"Matrix A:\n{A}")

Matrix A:
[[ 4 -2]
 [ 1  1]]


In [24]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = LA.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns):\n{eigenvectors}")

Eigenvalues: [3. 2.]
Eigenvectors (columns):
[[0.894 0.707]
 [0.447 0.707]]


In [25]:
# Verify: Av = lambda * v
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    print(f"A @ v{i}: {A @ v}")
    print(f"lambda * v{i}: {lam * v}")
    print()

A @ v0: [2.683 1.342]
lambda * v0: [2.683 1.342]

A @ v1: [1.414 1.414]
lambda * v1: [1.414 1.414]



In [26]:
# For symmetric matrices, use eigh (faster, more stable)
B = np.array([[4, 2], [2, 3]])
eigenvalues, eigenvectors = LA.eigh(B)
print(f"Eigenvalues (symmetric): {eigenvalues}")

Eigenvalues (symmetric): [1.438 5.562]


In [27]:
# Only eigenvalues
eigenvalues_only = LA.eigvals(A)
print(f"Eigenvalues only: {eigenvalues_only}")

Eigenvalues only: [3. 2.]


---
## 6. Singular Value Decomposition (SVD)

In [28]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(f"Matrix A (4x3):\n{A}")

Matrix A (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
# Full SVD: A = U @ S @ V^T
U, s, Vt = LA.svd(A)

print(f"U shape: {U.shape}")
print(f"Singular values: {s}")
print(f"V^T shape: {Vt.shape}")

U shape: (4, 4)
Singular values: [25.462  1.291  0.   ]
V^T shape: (3, 3)


In [30]:
# Reconstruct A
# Need to create diagonal matrix from s
S = np.zeros((4, 3))
np.fill_diagonal(S, s)

A_reconstructed = U @ S @ Vt
print(f"Reconstructed:\n{A_reconstructed}")

Reconstructed:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [31]:
# Low-rank approximation
# Keep only first k singular values
k = 1
A_approx = U[:, :k] @ np.diag(s[:k]) @ Vt[:k, :]
print(f"Rank-{k} approximation:\n{A_approx}")

Rank-1 approximation:
[[ 1.81   2.061  2.312]
 [ 4.419  5.031  5.644]
 [ 7.027  8.002  8.977]
 [ 9.636 10.973 12.309]]


---
## 7. Other Decompositions

In [32]:
# QR Decomposition: A = QR
A = np.array([[1, 2], [3, 4], [5, 6]])

Q, R = LA.qr(A)
print(f"Q (orthogonal):\n{Q}")
print(f"R (upper triangular):\n{R}")
print(f"Q @ R:\n{Q @ R}")

Q (orthogonal):
[[-0.169  0.897]
 [-0.507  0.276]
 [-0.845 -0.345]]
R (upper triangular):
[[-5.916 -7.437]
 [ 0.     0.828]]
Q @ R:
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [33]:
# Cholesky Decomposition: A = L @ L^T (for positive definite matrices)
A = np.array([[4, 2], [2, 5]])

L = LA.cholesky(A)
print(f"L (lower triangular):\n{L}")
print(f"L @ L^T:\n{L @ L.T}")

L (lower triangular):
[[2. 0.]
 [1. 2.]]
L @ L^T:
[[4. 2.]
 [2. 5.]]


---
## 8. Practical Applications

In [34]:
# Linear regression using normal equation
# y = X @ w
# w = (X^T X)^(-1) X^T y

np.random.seed(42)
X = np.column_stack([np.ones(100), np.random.rand(100)])  # Add bias
true_weights = np.array([2, 3])  # intercept=2, slope=3
y = X @ true_weights + np.random.randn(100) * 0.1

# Solve using normal equation
w = LA.inv(X.T @ X) @ X.T @ y
print(f"True weights: {true_weights}")
print(f"Estimated weights: {w}")

True weights: [2 3]
Estimated weights: [2.022 2.954]


In [35]:
# Better: using least squares
w_lstsq, _, _, _ = LA.lstsq(X, y, rcond=None)
print(f"Weights (lstsq): {w_lstsq}")

Weights (lstsq): [2.022 2.954]


In [36]:
# PCA using SVD
data = np.random.randn(100, 5)  # 100 samples, 5 features

# Center the data
data_centered = data - data.mean(axis=0)

# SVD
U, s, Vt = LA.svd(data_centered, full_matrices=False)

# Principal components are rows of Vt
print(f"Principal components shape: {Vt.shape}")

# Variance explained
variance_explained = (s ** 2) / np.sum(s ** 2)
print(f"Variance explained by each PC: {variance_explained}")

Principal components shape: (5, 5)
Variance explained by each PC: [0.28  0.241 0.192 0.152 0.134]


In [37]:
# Cosine similarity
def cosine_similarity(a, b):
    return np.dot(a, b) / (LA.norm(a) * LA.norm(b))

v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
v3 = np.array([-1, -2, -3])
v4 = np.array([1, 0, 0])

print(f"Similarity (v1, v2): {cosine_similarity(v1, v2):.4f}")  # 1.0 (identical)
print(f"Similarity (v1, v3): {cosine_similarity(v1, v3):.4f}")  # -1.0 (opposite)
print(f"Similarity (v1, v4): {cosine_similarity(v1, v4):.4f}")  # ~0.27

Similarity (v1, v2): 1.0000
Similarity (v1, v3): -1.0000
Similarity (v1, v4): 0.2673


---
## Key Points Summary

**Matrix Operations:**
- `@` or `np.dot()`: Matrix multiplication
- `*`: Element-wise multiplication
- `LA.inv()`: Matrix inverse
- `LA.det()`: Determinant

**Decompositions:**
- `LA.eig()`: Eigendecomposition
- `LA.svd()`: Singular Value Decomposition
- `LA.qr()`: QR decomposition
- `LA.cholesky()`: Cholesky decomposition

**Solving Systems:**
- `LA.solve()`: Solve Ax = b
- `LA.lstsq()`: Least squares solution

---
## Interview Tips

**Q1: When to use @ vs * for matrices?**
> - `@`: Matrix multiplication (dot product)
> - `*`: Element-wise (Hadamard) product
> - Common mistake: using * when @ is needed

**Q2: Why use LA.solve() instead of inverse?**
> - solve() is faster and more numerically stable
> - Computing inverse requires more operations
> - Inverse can amplify numerical errors

**Q3: What are singular values used for?**
> - Measure matrix "size" in different directions
> - Rank determination
> - Low-rank approximation (dimensionality reduction)
> - Condition number = ratio of largest to smallest

**Q4: How is SVD related to PCA?**
> For centered data X: SVD gives X = U * S * Vt
> - Principal components are rows of Vt
> - Singular values relate to variance explained

---
## Practice Exercises

### Exercise 1: Verify matrix inverse

In [38]:
# Create 3x3 matrix and verify that A @ A_inv = I
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])


In [39]:
# Solution
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
A_inv = LA.inv(A)

print(f"A @ A_inv:\n{A @ A_inv}")
print(f"Is close to identity: {np.allclose(A @ A_inv, np.eye(3))}")

A @ A_inv:
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
Is close to identity: True


### Exercise 2: Project vector onto another vector

In [40]:
# Project vector a onto vector b
# Formula: proj_b(a) = (a.b / b.b) * b
a = np.array([3, 4])
b = np.array([1, 0])


In [41]:
# Solution
a = np.array([3, 4])
b = np.array([1, 0])

projection = (np.dot(a, b) / np.dot(b, b)) * b
print(f"a: {a}")
print(f"b: {b}")
print(f"Projection of a onto b: {projection}")

a: [3 4]
b: [1 0]
Projection of a onto b: [3. 0.]


### Exercise 3: Compute matrix power

In [42]:
# Compute A^3 (A @ A @ A)
A = np.array([[1, 2], [3, 4]])


In [43]:
# Solution
A = np.array([[1, 2], [3, 4]])

# Method 1: Using matrix_power
A_cubed = LA.matrix_power(A, 3)
print(f"A^3 (matrix_power):\n{A_cubed}")

# Method 2: Manual
A_cubed_manual = A @ A @ A
print(f"A^3 (manual):\n{A_cubed_manual}")

A^3 (matrix_power):
[[ 37  54]
 [ 81 118]]
A^3 (manual):
[[ 37  54]
 [ 81 118]]


---
## Next Notebook
**04_trigonometric_and_exponential.ipynb** - Trigonometric, exponential, and logarithmic functions.