# Reshape and Resize Operations

**Module 02 | Notebook 01**

---

## Objective
By the end of this notebook, you will master:
- Reshaping arrays without changing data
- Flattening and raveling arrays
- Resizing arrays (with data modification)
- Understanding views vs copies in reshaping
- Common reshape patterns and pitfalls

In [2]:
import numpy as np
np.set_printoptions(precision=2)

---
## 1. Understanding Shape

In [3]:
# Shape represents dimensions
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D: shape={arr_1d.shape}, ndim={arr_1d.ndim}, size={arr_1d.size}")
print(f"2D: shape={arr_2d.shape}, ndim={arr_2d.ndim}, size={arr_2d.size}")
print(f"3D: shape={arr_3d.shape}, ndim={arr_3d.ndim}, size={arr_3d.size}")

1D: shape=(6,), ndim=1, size=6
2D: shape=(2, 3), ndim=2, size=6
3D: shape=(2, 2, 2), ndim=3, size=8


---
## 2. reshape() - Change Shape Without Changing Data

In [4]:
# Basic reshape
arr = np.arange(12)
print(f"Original 1D: {arr}")

# Reshape to 2D
arr_2d = arr.reshape(3, 4)  # 3 rows, 4 columns
print(f"Reshaped to (3,4):\n{arr_2d}")

# Reshape to 3D
arr_3d = arr.reshape(2, 2, 3)  # 2 blocks, 2 rows, 3 columns
print(f"Reshaped to (2,2,3):\n{arr_3d}")

Original 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to (2,2,3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
# Using -1 for automatic dimension calculation
arr = np.arange(24)

# Let NumPy figure out one dimension
print(f"reshape(4, -1): {arr.reshape(4, -1).shape}")  # (4, 6)
print(f"reshape(-1, 3): {arr.reshape(-1, 3).shape}")  # (8, 3)
print(f"reshape(2, -1, 4): {arr.reshape(2, -1, 4).shape}")  # (2, 3, 4)

reshape(4, -1): (4, 6)
reshape(-1, 3): (8, 3)
reshape(2, -1, 4): (2, 3, 4)


In [6]:
# Reshape returns a VIEW (usually)
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

print(f"Shares memory? {np.shares_memory(arr, reshaped)}")

# Modifying reshaped affects original
reshaped[0, 0] = 999
print(f"Original after modification: {arr[:4]}")

Shares memory? True
Original after modification: [999   1   2   3]


In [7]:
# Invalid reshape - size must match!
arr = np.arange(12)
try:
    arr.reshape(3, 5)  # 3*5=15 != 12
except ValueError as e:
    print(f"Error: {e}")

Error: cannot reshape array of size 12 into shape (3,5)


### Row-major (C) vs Column-major (F) Order

In [8]:
arr = np.arange(6)
print(f"Original: {arr}")

# C-order (row-major) - default
c_order = arr.reshape(2, 3, order='C')
print(f"C-order (row-major):\n{c_order}")

# F-order (column-major)
f_order = arr.reshape(2, 3, order='F')
print(f"F-order (column-major):\n{f_order}")

Original: [0 1 2 3 4 5]
C-order (row-major):
[[0 1 2]
 [3 4 5]]
F-order (column-major):
[[0 2 4]
 [1 3 5]]


---
## 3. flatten() vs ravel() - Convert to 1D

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original:\n{arr}")

Original:
[[1 2 3]
 [4 5 6]]


In [10]:
# flatten() - ALWAYS returns a COPY
flat = arr.flatten()
print(f"flatten(): {flat}")
print(f"Is copy? {not np.shares_memory(arr, flat)}")

# Modifying doesn't affect original
flat[0] = 999
print(f"Original unchanged: {arr[0, 0]}")

flatten(): [1 2 3 4 5 6]
Is copy? True
Original unchanged: 1


In [11]:
# ravel() - Returns a VIEW when possible
arr = np.array([[1, 2, 3], [4, 5, 6]])
raveled = arr.ravel()
print(f"ravel(): {raveled}")
print(f"Shares memory? {np.shares_memory(arr, raveled)}")

# Modifying DOES affect original
raveled[0] = 999
print(f"Original changed: {arr[0, 0]}")

ravel(): [1 2 3 4 5 6]
Shares memory? True
Original changed: 999


In [12]:
# Order parameter for flatten/ravel
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"C-order (row): {arr.flatten('C')}")  # [1, 2, 3, 4, 5, 6]
print(f"F-order (col): {arr.flatten('F')}")  # [1, 4, 2, 5, 3, 6]

C-order (row): [1 2 3 4 5 6]
F-order (col): [1 4 2 5 3 6]


In [13]:
# Using reshape(-1) as alternative to ravel
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.reshape(-1)
print(f"reshape(-1): {flattened}")
print(f"Shares memory? {np.shares_memory(arr, flattened)}")

reshape(-1): [1 2 3 4 5 6]
Shares memory? True


---
## 4. resize() - Change Shape WITH Data Modification

In [14]:
# np.resize() - returns new array, repeats data if needed
arr = np.array([1, 2, 3, 4])

# Larger size - repeats data
larger = np.resize(arr, (3, 3))
print(f"Original: {arr}")
print(f"Resized to (3,3):\n{larger}")

# Smaller size - truncates
smaller = np.resize(arr, (2,))
print(f"Resized to (2,): {smaller}")

Original: [1 2 3 4]
Resized to (3,3):
[[1 2 3]
 [4 1 2]
 [3 4 1]]
Resized to (2,): [1 2]


In [15]:
# arr.resize() - in-place modification (more restrictive)
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"Before: shape={arr.shape}")

arr.resize(2, 3)  # In-place
print(f"After resize(2,3):\n{arr}")

Before: shape=(6,)
After resize(2,3):
[[1 2 3]
 [4 5 6]]


In [16]:
# In-place resize with refcheck=False can expand with zeros
arr = np.array([1, 2, 3])
arr.resize(6, refcheck=False)  # Pads with zeros
print(f"Expanded with zeros: {arr}")

Expanded with zeros: [1 2 3 0 0 0]


---
## 5. Adding and Removing Dimensions

In [17]:
# np.expand_dims - add new axis
arr = np.array([1, 2, 3, 4])
print(f"Original: shape={arr.shape}")

# Add axis at position 0
expanded_0 = np.expand_dims(arr, axis=0)
print(f"expand_dims(axis=0): shape={expanded_0.shape}")

# Add axis at position 1
expanded_1 = np.expand_dims(arr, axis=1)
print(f"expand_dims(axis=1): shape={expanded_1.shape}")

Original: shape=(4,)
expand_dims(axis=0): shape=(1, 4)
expand_dims(axis=1): shape=(4, 1)


In [18]:
# Using np.newaxis (equivalent)
arr = np.array([1, 2, 3, 4])

row = arr[np.newaxis, :]  # (1, 4)
col = arr[:, np.newaxis]  # (4, 1)

print(f"Row vector shape: {row.shape}")
print(f"Column vector shape: {col.shape}")

Row vector shape: (1, 4)
Column vector shape: (4, 1)


In [19]:
# np.squeeze - remove dimensions of size 1
arr = np.array([[[1, 2, 3]]])  # shape (1, 1, 3)
print(f"Original shape: {arr.shape}")

squeezed = np.squeeze(arr)
print(f"Squeezed shape: {squeezed.shape}")  # (3,)

# Squeeze specific axis
arr = np.zeros((1, 3, 1, 4))
print(f"Original: {arr.shape}")
print(f"Squeeze axis 0: {np.squeeze(arr, axis=0).shape}")
print(f"Squeeze axis 2: {np.squeeze(arr, axis=2).shape}")

Original shape: (1, 1, 3)
Squeezed shape: (3,)
Original: (1, 3, 1, 4)
Squeeze axis 0: (3, 1, 4)
Squeeze axis 2: (1, 3, 4)


---
## 6. Practical Reshape Examples

In [20]:
# Image data reshaping (common in ML)
# Imagine 100 images of 28x28 pixels, 3 color channels
images = np.random.rand(100, 28, 28, 3)
print(f"Original images shape: {images.shape}")

# Flatten for fully connected layer
flattened = images.reshape(100, -1)
print(f"Flattened for FC: {flattened.shape}")  # (100, 2352)

# Add batch dimension to single image
single_image = np.random.rand(28, 28, 3)
batched = single_image[np.newaxis, ...]  # or reshape(1, 28, 28, 3)
print(f"Single image batched: {batched.shape}")

Original images shape: (100, 28, 28, 3)
Flattened for FC: (100, 2352)
Single image batched: (1, 28, 28, 3)


In [21]:
# Time series windowing
data = np.arange(100)  # 100 time steps
window_size = 10

# Create overlapping windows using stride tricks (advanced)
# Simple approach: non-overlapping windows
windows = data.reshape(-1, window_size)
print(f"Windows shape: {windows.shape}")  # (10, 10)
print(f"First window: {windows[0]}")

Windows shape: (10, 10)
First window: [0 1 2 3 4 5 6 7 8 9]


In [22]:
# Matrix to vector and back
matrix = np.arange(12).reshape(3, 4)
print(f"Matrix:\n{matrix}")

# Store original shape
original_shape = matrix.shape

# Process as vector
vector = matrix.ravel()
vector = vector * 2  # Some operation

# Restore shape
result = vector.reshape(original_shape)
print(f"Result:\n{result}")

Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Result:
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


---
## Key Points Summary

| Function | Returns | Data Change | Notes |
|----------|---------|-------------|-------|
| `reshape()` | View (usually) | No | Size must match |
| `flatten()` | Copy | No | Always copies |
| `ravel()` | View (when possible) | No | Faster than flatten |
| `np.resize()` | New array | Yes | Repeats/truncates data |
| `arr.resize()` | In-place | Yes | Modifies original |
| `expand_dims()` | View | No | Adds axis |
| `squeeze()` | View | No | Removes size-1 axes |

**Key Rules:**
- `reshape`: Total elements must remain same
- Use `-1` to auto-calculate one dimension
- `flatten` for safety (copy), `ravel` for speed (view)
- Views share memory - modifications propagate!

---
## Interview Tips

**Q1: What is the difference between reshape(-1) and flatten()?**
> - `reshape(-1)` returns a view (when possible)
> - `flatten()` always returns a copy
> - Use flatten when you need independent copy, reshape for efficiency

**Q2: When does reshape return a copy instead of view?**
> When the array is non-contiguous in memory (e.g., after transpose or non-contiguous slicing). You can force contiguous with `.copy()` first.

**Q3: How do you add a batch dimension to a single sample?**
> Use `arr[np.newaxis, ...]` or `arr.reshape(1, *arr.shape)` or `np.expand_dims(arr, 0)`

**Q4: What happens if reshape size doesn't match?**
> Raises `ValueError: cannot reshape array of size X into shape Y`

---
## Practice Exercises

### Exercise 1: Reshape a 1D array of 24 elements into all possible 2D shapes

In [23]:
# Your code here


In [24]:
# Solution
arr = np.arange(24)
# Find all factor pairs of 24
shapes = [(1, 24), (2, 12), (3, 8), (4, 6), (6, 4), (8, 3), (12, 2), (24, 1)]
for shape in shapes:
    reshaped = arr.reshape(shape)
    print(f"Shape {shape}: valid")

Shape (1, 24): valid
Shape (2, 12): valid
Shape (3, 8): valid
Shape (4, 6): valid
Shape (6, 4): valid
Shape (8, 3): valid
Shape (12, 2): valid
Shape (24, 1): valid


### Exercise 2: Convert a batch of images (N, H, W, C) to (N, C, H, W) format

In [25]:
# Your code here
images = np.random.rand(10, 32, 32, 3)  # NHWC format


In [26]:
# Solution
images = np.random.rand(10, 32, 32, 3)  # NHWC format
print(f"Original (NHWC): {images.shape}")

# Use transpose, not reshape!
images_nchw = images.transpose(0, 3, 1, 2)
print(f"Converted (NCHW): {images_nchw.shape}")

Original (NHWC): (10, 32, 32, 3)
Converted (NCHW): (10, 3, 32, 32)


### Exercise 3: Verify view vs copy behavior

In [27]:
# Create array and test which operations create views
arr = np.arange(12)

# Test these and predict view or copy:
a = arr.reshape(3, 4)
b = arr.flatten()
c = arr.ravel()
d = np.resize(arr, (4, 4))


In [28]:
# Solution
arr = np.arange(12)

a = arr.reshape(3, 4)
b = arr.flatten()
c = arr.ravel()
d = np.resize(arr, (4, 4))

print(f"reshape: {'view' if np.shares_memory(arr, a) else 'copy'}")
print(f"flatten: {'view' if np.shares_memory(arr, b) else 'copy'}")
print(f"ravel: {'view' if np.shares_memory(arr, c) else 'copy'}")
print(f"resize: {'view' if np.shares_memory(arr, d) else 'copy'}")

reshape: view
flatten: copy
ravel: view
resize: copy


---
## Next Notebook
**02_concatenate_and_split.ipynb** - Joining and splitting arrays: concatenate, append, split, and more.