# Stacking and Tiling Operations

**Module 02 | Notebook 03**

---

## Objective
By the end of this notebook, you will master:
- Stack operations (creating new dimensions)
- Horizontal, vertical, and depth stacking
- Tiling and repeating arrays
- Practical applications of stacking/tiling

In [2]:
import numpy as np
np.set_printoptions(precision=2)

---
## 1. np.stack() - Stack Along NEW Axis

In [3]:
# Key difference from concatenate:
# concatenate: joins along EXISTING axis
# stack: creates NEW axis, then stacks

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print(f"Array a: {a}, shape: {a.shape}")
print(f"Array b: {b}, shape: {b.shape}")

Array a: [1 2 3], shape: (3,)
Array b: [4 5 6], shape: (3,)


In [4]:
# Stack along axis=0 (new first dimension)
stacked_0 = np.stack([a, b, c], axis=0)
print(f"stack axis=0:\n{stacked_0}")
print(f"Shape: {stacked_0.shape}")  # (3, 3)

stack axis=0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [5]:
# Stack along axis=1 (new second dimension)
stacked_1 = np.stack([a, b, c], axis=1)
print(f"stack axis=1:\n{stacked_1}")
print(f"Shape: {stacked_1.shape}")  # (3, 3)

stack axis=1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (3, 3)


In [6]:
# Compare with concatenate
concat = np.concatenate([[a], [b], [c]], axis=0)
print(f"concatenate:\n{concat}")
print(f"Shape: {concat.shape}")  # Same result as stack axis=0 in this case

concatenate:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [7]:
# Stack 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"arr1 shape: {arr1.shape}")
print(f"arr2 shape: {arr2.shape}")

# Stack creates 3D array
stacked = np.stack([arr1, arr2], axis=0)
print(f"Stacked axis=0 shape: {stacked.shape}")  # (2, 2, 2)
print(f"Stacked:\n{stacked}")

arr1 shape: (2, 2)
arr2 shape: (2, 2)
Stacked axis=0 shape: (2, 2, 2)
Stacked:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---
## 2. Specialized Stack Functions

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"a: {a}")
print(f"b: {b}")

a: [1 2 3]
b: [4 5 6]


In [9]:
# hstack - horizontal stack (column-wise)
hstacked = np.hstack([a, b])
print(f"hstack: {hstacked}")  # [1, 2, 3, 4, 5, 6]
print(f"Shape: {hstacked.shape}")

hstack: [1 2 3 4 5 6]
Shape: (6,)


In [10]:
# vstack - vertical stack (row-wise)
vstacked = np.vstack([a, b])
print(f"vstack:\n{vstacked}")
print(f"Shape: {vstacked.shape}")  # (2, 3)

vstack:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [11]:
# dstack - depth stack (along third axis)
dstacked = np.dstack([a, b])
print(f"dstack:\n{dstacked}")
print(f"Shape: {dstacked.shape}")  # (1, 3, 2)

dstack:
[[[1 4]
  [2 5]
  [3 6]]]
Shape: (1, 3, 2)


In [12]:
# With 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"hstack (2D):\n{np.hstack([arr1, arr2])}")  # (2, 4)
print()
print(f"vstack (2D):\n{np.vstack([arr1, arr2])}")  # (4, 2)
print()
print(f"dstack (2D) shape: {np.dstack([arr1, arr2]).shape}")  # (2, 2, 2)

hstack (2D):
[[1 2 5 6]
 [3 4 7 8]]

vstack (2D):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

dstack (2D) shape: (2, 2, 2)


---
## 3. np.column_stack() and np.row_stack()

In [13]:
# column_stack - stack 1D arrays as columns
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

cols = np.column_stack([a, b, c])
print(f"column_stack:\n{cols}")
print(f"Shape: {cols.shape}")  # (3, 3)

column_stack:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (3, 3)


In [14]:
# row_stack - same as vstack
rows = np.row_stack([a, b, c])
print(f"row_stack:\n{rows}")
print(f"Shape: {rows.shape}")  # (3, 3)

row_stack:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_44568\1831292537.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  rows = np.row_stack([a, b, c])


In [15]:
# Useful for building feature matrices
feature1 = np.array([1.0, 2.0, 3.0])  # Height
feature2 = np.array([60, 70, 80])     # Weight
feature3 = np.array([25, 30, 35])     # Age

# Each column is a feature
X = np.column_stack([feature1, feature2, feature3])
print(f"Feature matrix:\n{X}")
print(f"Shape (samples, features): {X.shape}")

Feature matrix:
[[ 1. 60. 25.]
 [ 2. 70. 30.]
 [ 3. 80. 35.]]
Shape (samples, features): (3, 3)


---
## 4. np.tile() - Repeat Array as Tiles

In [16]:
# 1D tiling
arr = np.array([1, 2, 3])

# Repeat 3 times
tiled = np.tile(arr, 3)
print(f"tile(arr, 3): {tiled}")

tile(arr, 3): [1 2 3 1 2 3 1 2 3]


In [17]:
# 2D tiling with tuple
arr = np.array([1, 2, 3])

# (rows, cols) repetition
tiled_2d = np.tile(arr, (2, 3))  # 2 rows, 3 column-repetitions
print(f"tile(arr, (2,3)):\n{tiled_2d}")

tile(arr, (2,3)):
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [18]:
# Tile a 2D array
arr = np.array([[1, 2], [3, 4]])
print(f"Original:\n{arr}")

tiled = np.tile(arr, (2, 3))  # 2x3 grid of tiles
print(f"tile((2,3)):\n{tiled}")

Original:
[[1 2]
 [3 4]]
tile((2,3)):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


---
## 5. np.repeat() - Repeat Elements

In [19]:
# Key difference:
# tile: repeats the WHOLE array
# repeat: repeats EACH element

arr = np.array([1, 2, 3])

print(f"tile(arr, 3): {np.tile(arr, 3)}")
print(f"repeat(arr, 3): {np.repeat(arr, 3)}")

tile(arr, 3): [1 2 3 1 2 3 1 2 3]
repeat(arr, 3): [1 1 1 2 2 2 3 3 3]


In [20]:
# Different repeat counts per element
arr = np.array([1, 2, 3])
repeated = np.repeat(arr, [2, 3, 4])
print(f"repeat([1,2,3], [2,3,4]): {repeated}")

repeat([1,2,3], [2,3,4]): [1 1 2 2 2 3 3 3 3]


In [21]:
# 2D repeat
arr = np.array([[1, 2], [3, 4]])
print(f"Original:\n{arr}")

# Repeat along axis 0 (rows)
rep_rows = np.repeat(arr, 2, axis=0)
print(f"repeat axis=0:\n{rep_rows}")

# Repeat along axis 1 (columns)
rep_cols = np.repeat(arr, 2, axis=1)
print(f"repeat axis=1:\n{rep_cols}")

Original:
[[1 2]
 [3 4]]
repeat axis=0:
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
repeat axis=1:
[[1 1 2 2]
 [3 3 4 4]]


In [22]:
# Without axis - flattens first
arr = np.array([[1, 2], [3, 4]])
flat_repeat = np.repeat(arr, 2)  # No axis
print(f"repeat without axis: {flat_repeat}")

repeat without axis: [1 1 2 2 3 3 4 4]


---
## 6. Comparison: tile vs repeat vs broadcast

In [23]:
arr = np.array([1, 2, 3])

# All produce same visual result but different!
print("tile:")
tiled = np.tile(arr, (3, 1))
print(tiled)

print("\nrepeat + reshape:")
repeated = np.repeat(arr[np.newaxis, :], 3, axis=0)
print(repeated)

print("\nbroadcast_to (no copy!):")
broadcasted = np.broadcast_to(arr, (3, 3))
print(broadcasted)

tile:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

repeat + reshape:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

broadcast_to (no copy!):
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
# Memory comparison
arr = np.arange(1000)

tiled = np.tile(arr, (100, 1))
broadcasted = np.broadcast_to(arr, (100, 1000))

print(f"Tiled memory: {tiled.nbytes / 1024:.1f} KB")
print(f"Broadcasted memory: {broadcasted.nbytes / 1024:.1f} KB")
# broadcast_to creates a VIEW with strides, much less memory!

Tiled memory: 781.2 KB
Broadcasted memory: 781.2 KB


---
## 7. Practical Applications

In [25]:
# Create RGB image from grayscale
grayscale = np.random.randint(0, 256, (4, 4), dtype=np.uint8)
print(f"Grayscale:\n{grayscale}")

# Stack to create RGB (same values in R, G, B)
rgb = np.stack([grayscale, grayscale, grayscale], axis=-1)
print(f"RGB shape: {rgb.shape}")

Grayscale:
[[ 60  51 199 159]
 [ 40 241  67 108]
 [ 30 235 171  88]
 [ 79 127 253 244]]
RGB shape: (4, 4, 3)


In [26]:
# Create batch from single sample
sample = np.random.rand(28, 28)  # Single MNIST-like image
batch_size = 32

# Method 1: tile
batch = np.tile(sample[np.newaxis, :, :], (batch_size, 1, 1))
print(f"Batch shape: {batch.shape}")

Batch shape: (32, 28, 28)


In [27]:
# Create coordinate grid
x = np.arange(5)
y = np.arange(3)

# Using meshgrid
xx, yy = np.meshgrid(x, y)
print(f"X grid:\n{xx}")
print(f"Y grid:\n{yy}")

# Stack coordinates
coords = np.stack([xx, yy], axis=-1)
print(f"Coordinate pairs shape: {coords.shape}")

X grid:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Y grid:
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
Coordinate pairs shape: (3, 5, 2)


In [28]:
# Data augmentation: duplicate with noise
original = np.array([[1, 2], [3, 4]], dtype=float)
n_augmentations = 3

# Tile and add noise
tiled = np.tile(original, (n_augmentations, 1, 1))
noise = np.random.normal(0, 0.1, tiled.shape)
augmented = tiled + noise

print(f"Augmented shape: {augmented.shape}")
print(f"First augmentation:\n{augmented[0]}")

Augmented shape: (3, 2, 2)
First augmentation:
[[0.91 1.96]
 [3.07 3.9 ]]


---
## Key Points Summary

**Stacking (creates new axis):**
| Function | Description | Result Shape |
|----------|-------------|-------------|
| `np.stack([a,b], axis=0)` | Stack along new axis 0 | (2, *a.shape) |
| `np.vstack([a,b])` | Vertical stack | (2, n) for 1D |
| `np.hstack([a,b])` | Horizontal stack | (2n,) for 1D |
| `np.dstack([a,b])` | Depth stack (axis 2) | (1, n, 2) for 1D |
| `np.column_stack([a,b])` | Stack as columns | (n, 2) for 1D |

**Tiling/Repeating:**
| Function | Description |
|----------|-------------|
| `np.tile(arr, reps)` | Tile whole array |
| `np.repeat(arr, n)` | Repeat each element |
| `np.broadcast_to(arr, shape)` | Virtual repeat (no copy) |

---
## Interview Tips

**Q1: What is the difference between np.stack and np.concatenate?**
> - `stack` creates a NEW dimension and stacks along it
> - `concatenate` joins along EXISTING dimension
> - Two (3,) arrays: stack -> (2,3), concat -> (6,)

**Q2: When should you use broadcast_to instead of tile?**
> When you need to avoid memory overhead. broadcast_to creates a view using strides, while tile creates a full copy. Use broadcast_to for read-only operations.

**Q3: How do you combine multiple feature arrays into a feature matrix?**
> Use `np.column_stack([f1, f2, f3])` where each fi is a 1D array of same length. Result has each feature as a column.

**Q4: What is the difference between tile and repeat?**
> - `tile([1,2,3], 2)` = [1,2,3,1,2,3] (tiles whole array)
> - `repeat([1,2,3], 2)` = [1,1,2,2,3,3] (repeats each element)

---
## Practice Exercises

### Exercise 1: Create a 3-channel image from 3 separate channel arrays

In [29]:
# Given R, G, B channels (each 4x4), create RGB image of shape (4, 4, 3)
R = np.random.randint(0, 256, (4, 4))
G = np.random.randint(0, 256, (4, 4))
B = np.random.randint(0, 256, (4, 4))


In [30]:
# Solution
R = np.random.randint(0, 256, (4, 4))
G = np.random.randint(0, 256, (4, 4))
B = np.random.randint(0, 256, (4, 4))

# Method 1: dstack
rgb1 = np.dstack([R, G, B])
print(f"dstack shape: {rgb1.shape}")

# Method 2: stack with axis=-1
rgb2 = np.stack([R, G, B], axis=-1)
print(f"stack axis=-1 shape: {rgb2.shape}")

dstack shape: (4, 4, 3)
stack axis=-1 shape: (4, 4, 3)


### Exercise 2: Create a checkerboard pattern using tile

In [31]:
# Create an 8x8 checkerboard (0s and 1s alternating)


In [32]:
# Solution
# Base 2x2 pattern
base = np.array([[0, 1], [1, 0]])

# Tile to 8x8
checkerboard = np.tile(base, (4, 4))
print(f"Checkerboard:\n{checkerboard}")

Checkerboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Exercise 3: Interleave two arrays

In [33]:
# Given [1, 2, 3] and [10, 20, 30], create [1, 10, 2, 20, 3, 30]
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])


In [34]:
# Solution
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Stack then flatten in Fortran order
interleaved = np.stack([a, b], axis=1).flatten()
print(f"Interleaved: {interleaved}")

# Or using ravel
interleaved2 = np.column_stack([a, b]).ravel()
print(f"Alternative: {interleaved2}")

Interleaved: [ 1 10  2 20  3 30]
Alternative: [ 1 10  2 20  3 30]


---
## Next Notebook
**04_transposing_and_swapping.ipynb** - Transpose, swapaxes, and moveaxis operations.