# Transposing and Swapping Axes

**Module 02 | Notebook 04**

---

## Objective
By the end of this notebook, you will master:
- Transposing 2D and ND arrays
- Swapping and moving axes
- Rolling and flipping arrays
- Practical applications in data manipulation

In [2]:
import numpy as np
np.set_printoptions(precision=2)

---
## 1. Transpose - 2D Arrays

In [3]:
# 2D transpose: swap rows and columns
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original (2x3):\n{arr}")
print(f"Shape: {arr.shape}")

Original (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [4]:
# Method 1: .T property
transposed = arr.T
print(f"Transposed (3x2):\n{transposed}")
print(f"Shape: {transposed.shape}")

Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [5]:
# Method 2: transpose() method
transposed = arr.transpose()
print(f"Using transpose():\n{transposed}")

Using transpose():
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# Method 3: np.transpose() function
transposed = np.transpose(arr)
print(f"Using np.transpose():\n{transposed}")

Using np.transpose():
[[1 4]
 [2 5]
 [3 6]]


In [7]:
# Transpose returns a VIEW
arr = np.arange(6).reshape(2, 3)
trans = arr.T

print(f"Shares memory? {np.shares_memory(arr, trans)}")

# Modifying affects original
trans[0, 0] = 999
print(f"Original after modification:\n{arr}")

Shares memory? True
Original after modification:
[[999   1   2]
 [  3   4   5]]


---
## 2. Transpose - ND Arrays

In [8]:
# 3D array transpose
arr = np.arange(24).reshape(2, 3, 4)
print(f"Original shape: {arr.shape}")  # (2, 3, 4)

Original shape: (2, 3, 4)


In [9]:
# Default transpose reverses all axes
trans = arr.T
print(f"Default .T shape: {trans.shape}")  # (4, 3, 2)

Default .T shape: (4, 3, 2)


In [10]:
# Custom axis order with transpose()
# Specify desired order of axes

# Original axes: 0, 1, 2 (shape 2, 3, 4)
# New order: 1, 0, 2
trans_custom = arr.transpose(1, 0, 2)
print(f"transpose(1, 0, 2) shape: {trans_custom.shape}")  # (3, 2, 4)

transpose(1, 0, 2) shape: (3, 2, 4)


In [11]:
# Example: NHWC to NCHW format (common in deep learning)
# N=batch, H=height, W=width, C=channels

images_nhwc = np.random.rand(32, 224, 224, 3)  # TensorFlow format
print(f"NHWC shape: {images_nhwc.shape}")

# Convert to NCHW (PyTorch format)
images_nchw = images_nhwc.transpose(0, 3, 1, 2)
print(f"NCHW shape: {images_nchw.shape}")

NHWC shape: (32, 224, 224, 3)
NCHW shape: (32, 3, 224, 224)


---
## 3. swapaxes() - Swap Two Axes

In [12]:
# swapaxes is simpler when you only need to swap two axes
arr = np.arange(24).reshape(2, 3, 4)
print(f"Original shape: {arr.shape}")

# Swap axis 0 and 1
swapped = np.swapaxes(arr, 0, 1)
print(f"swapaxes(0, 1) shape: {swapped.shape}")  # (3, 2, 4)

# Swap axis 1 and 2
swapped = np.swapaxes(arr, 1, 2)
print(f"swapaxes(1, 2) shape: {swapped.shape}")  # (2, 4, 3)

Original shape: (2, 3, 4)
swapaxes(0, 1) shape: (3, 2, 4)
swapaxes(1, 2) shape: (2, 4, 3)


In [13]:
# Equivalent operations
arr = np.arange(12).reshape(3, 4)

# These are equivalent for 2D:
print(f"T: {arr.T.shape}")
print(f"transpose: {arr.transpose().shape}")
print(f"swapaxes(0,1): {np.swapaxes(arr, 0, 1).shape}")

T: (4, 3)
transpose: (4, 3)
swapaxes(0,1): (4, 3)


---
## 4. moveaxis() - Move Axis to New Position

In [14]:
# moveaxis moves one axis to a new position, shifting others
arr = np.arange(24).reshape(2, 3, 4)
print(f"Original shape: {arr.shape}")  # (2, 3, 4)

Original shape: (2, 3, 4)


In [15]:
# Move axis 0 to position 2
moved = np.moveaxis(arr, 0, 2)
print(f"moveaxis(0, 2) shape: {moved.shape}")  # (3, 4, 2)

# Move axis 2 to position 0
moved = np.moveaxis(arr, 2, 0)
print(f"moveaxis(2, 0) shape: {moved.shape}")  # (4, 2, 3)

moveaxis(0, 2) shape: (3, 4, 2)
moveaxis(2, 0) shape: (4, 2, 3)


In [16]:
# Move multiple axes
arr = np.arange(120).reshape(2, 3, 4, 5)  # (2, 3, 4, 5)
print(f"Original shape: {arr.shape}")

# Move axes 0 and 1 to positions 2 and 3
moved = np.moveaxis(arr, [0, 1], [2, 3])
print(f"moveaxis([0,1], [2,3]) shape: {moved.shape}")  # (4, 5, 2, 3)

Original shape: (2, 3, 4, 5)
moveaxis([0,1], [2,3]) shape: (4, 5, 2, 3)


In [17]:
# Practical: Move channel axis
# Image with channels last (H, W, C) to channels first (C, H, W)
image = np.random.rand(224, 224, 3)
print(f"Channels last (HWC): {image.shape}")

image_chw = np.moveaxis(image, -1, 0)
print(f"Channels first (CHW): {image_chw.shape}")

Channels last (HWC): (224, 224, 3)
Channels first (CHW): (3, 224, 224)


---
## 5. rollaxis() - Legacy Axis Rotation

In [18]:
# rollaxis rolls the specified axis to a position
# Note: moveaxis is generally preferred for clarity

arr = np.arange(24).reshape(2, 3, 4)
print(f"Original shape: {arr.shape}")

# Roll axis 2 to position 0
rolled = np.rollaxis(arr, 2, 0)
print(f"rollaxis(2, 0) shape: {rolled.shape}")  # (4, 2, 3)

Original shape: (2, 3, 4)
rollaxis(2, 0) shape: (4, 2, 3)


---
## 6. Flipping Arrays

In [19]:
arr = np.arange(12).reshape(3, 4)
print(f"Original:\n{arr}")

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# np.flip - reverse along axis
flipped_all = np.flip(arr)  # All axes
print(f"flip all axes:\n{flipped_all}")

flip all axes:
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [21]:
# Flip specific axis
flipped_0 = np.flip(arr, axis=0)  # Flip rows
print(f"flip axis=0 (rows):\n{flipped_0}")

flipped_1 = np.flip(arr, axis=1)  # Flip columns
print(f"flip axis=1 (cols):\n{flipped_1}")

flip axis=0 (rows):
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
flip axis=1 (cols):
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [22]:
# Specialized flip functions
print(f"flipud (up-down):\n{np.flipud(arr)}")
print(f"fliplr (left-right):\n{np.fliplr(arr)}")

flipud (up-down):
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
fliplr (left-right):
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [23]:
# Using slicing for flip (also creates view)
print(f"arr[::-1] (flip rows):\n{arr[::-1]}")
print(f"arr[:, ::-1] (flip cols):\n{arr[:, ::-1]}")
print(f"arr[::-1, ::-1] (flip both):\n{arr[::-1, ::-1]}")

arr[::-1] (flip rows):
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
arr[:, ::-1] (flip cols):
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
arr[::-1, ::-1] (flip both):
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


---
## 7. Rolling Arrays (Circular Shift)

In [24]:
# np.roll - circular shift
arr = np.arange(10)
print(f"Original: {arr}")

# Roll right by 2
print(f"roll(2): {np.roll(arr, 2)}")

# Roll left by 2
print(f"roll(-2): {np.roll(arr, -2)}")

Original: [0 1 2 3 4 5 6 7 8 9]
roll(2): [8 9 0 1 2 3 4 5 6 7]
roll(-2): [2 3 4 5 6 7 8 9 0 1]


In [25]:
# 2D roll
arr = np.arange(12).reshape(3, 4)
print(f"Original:\n{arr}")

# Roll along axis 0 (rows)
print(f"roll(1, axis=0):\n{np.roll(arr, 1, axis=0)}")

# Roll along axis 1 (columns)
print(f"roll(1, axis=1):\n{np.roll(arr, 1, axis=1)}")

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
roll(1, axis=0):
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
roll(1, axis=1):
[[ 3  0  1  2]
 [ 7  4  5  6]
 [11  8  9 10]]


In [26]:
# Roll without axis - flattens first
print(f"roll(1) no axis: {np.roll(arr, 1)}")

roll(1) no axis: [[11  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


---
## 8. Rotating Arrays

In [27]:
# np.rot90 - rotate 90 degrees counterclockwise
arr = np.arange(12).reshape(3, 4)
print(f"Original:\n{arr}")

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# Rotate 90 degrees (counterclockwise)
rot90 = np.rot90(arr)
print(f"rot90 (1 turn):\n{rot90}")

# Rotate 180 degrees (2 turns)
rot180 = np.rot90(arr, k=2)
print(f"rot90 (2 turns):\n{rot180}")

# Rotate 270 degrees (3 turns) or -90 (clockwise)
rot270 = np.rot90(arr, k=3)
print(f"rot90 (3 turns):\n{rot270}")

rot90 (1 turn):
[[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 0  4  8]]
rot90 (2 turns):
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
rot90 (3 turns):
[[ 8  4  0]
 [ 9  5  1]
 [10  6  2]
 [11  7  3]]


In [29]:
# Clockwise rotation
clockwise = np.rot90(arr, k=-1)  # or k=3
print(f"Clockwise 90:\n{clockwise}")

Clockwise 90:
[[ 8  4  0]
 [ 9  5  1]
 [10  6  2]
 [11  7  3]]


---
## 9. Practical Applications

In [30]:
# Matrix multiplication with transposed matrix
A = np.random.rand(3, 4)
B = np.random.rand(3, 4)

# Multiply A with B transposed (A @ B.T)
result = A @ B.T
print(f"A shape: {A.shape}")
print(f"B.T shape: {B.T.shape}")
print(f"Result shape: {result.shape}")

A shape: (3, 4)
B.T shape: (4, 3)
Result shape: (3, 3)


In [31]:
# Covariance matrix (features as columns)
# Data: 100 samples, 5 features
data = np.random.rand(100, 5)

# Center the data
centered = data - data.mean(axis=0)

# Covariance: (X.T @ X) / (n-1)
cov = (centered.T @ centered) / (len(data) - 1)
print(f"Covariance matrix shape: {cov.shape}")

Covariance matrix shape: (5, 5)


In [32]:
# Image augmentation: random flips and rotations
image = np.random.rand(64, 64, 3)

# Horizontal flip
h_flip = np.fliplr(image)

# Vertical flip
v_flip = np.flipud(image)

# 90 degree rotation (need to handle channels)
rotated = np.rot90(image, axes=(0, 1))

print(f"Original: {image.shape}")
print(f"H-flip: {h_flip.shape}")
print(f"V-flip: {v_flip.shape}")
print(f"Rotated: {rotated.shape}")

Original: (64, 64, 3)
H-flip: (64, 64, 3)
V-flip: (64, 64, 3)
Rotated: (64, 64, 3)


In [33]:
# Time series: roll for creating lag features
prices = np.array([100, 102, 105, 103, 107])

# Previous day's price (lag 1)
lag1 = np.roll(prices, 1)
lag1[0] = np.nan  # First value has no previous

print(f"Prices: {prices}")
print(f"Lag 1: {lag1}")
print(f"Daily return: {prices - lag1}")

ValueError: cannot convert float NaN to integer

In [34]:
# 1. Initialize as float64 to support np.nan
prices = np.array([100, 102, 105, 103, 107], dtype=np.float64)

# 2. Roll for lag
lag1 = np.roll(prices, 1)
lag1[0] = np.nan 

print(f"Prices: {prices}")
print(f"Lag 1:  {lag1}")
print(f"Return: {prices - lag1}")

Prices: [100. 102. 105. 103. 107.]
Lag 1:  [ nan 100. 102. 105. 103.]
Return: [nan  2.  3. -2.  4.]


---
## Key Points Summary

**Transpose Operations:**
| Operation | Description | Returns |
|-----------|-------------|--------|
| `arr.T` | Reverse all axes | View |
| `arr.transpose(axes)` | Custom axis order | View |
| `np.swapaxes(a, ax1, ax2)` | Swap two axes | View |
| `np.moveaxis(a, src, dst)` | Move axis to new position | View |

**Flip/Rotate:**
| Operation | Description |
|-----------|-------------|
| `np.flip(arr, axis)` | Reverse along axis |
| `np.flipud(arr)` | Flip up-down (axis 0) |
| `np.fliplr(arr)` | Flip left-right (axis 1) |
| `np.roll(arr, shift, axis)` | Circular shift |
| `np.rot90(arr, k)` | Rotate k*90 degrees CCW |

---
## Interview Tips

**Q1: Does transpose create a copy?**
> No, transpose returns a VIEW. The data is not copied; only strides are modified. Modifications to the transposed array affect the original.

**Q2: How do you convert NHWC to NCHW format?**
> `arr.transpose(0, 3, 1, 2)` or `np.moveaxis(arr, -1, 1)`. This is common when converting between TensorFlow (NHWC) and PyTorch (NCHW) formats.

**Q3: Difference between swapaxes and transpose?**
> - `swapaxes` swaps exactly TWO axes
> - `transpose` can reorder ALL axes in any order
> - For swapping two axes, swapaxes is more readable

**Q4: How is roll different from shift?**
> `roll` is circular - elements that roll off one end appear at the other. There's no `shift` in NumPy, but you can achieve non-circular shift using slicing and padding.

---
## Practice Exercises

### Exercise 1: Convert batch of images between formats

In [35]:
# Given images in NCHW format (32, 3, 224, 224)
# Convert to NHWC format (32, 224, 224, 3)
images_nchw = np.random.rand(32, 3, 224, 224)


In [36]:
# Solution
images_nchw = np.random.rand(32, 3, 224, 224)
print(f"NCHW: {images_nchw.shape}")

# Method 1: transpose
images_nhwc = images_nchw.transpose(0, 2, 3, 1)
print(f"NHWC (transpose): {images_nhwc.shape}")

# Method 2: moveaxis
images_nhwc2 = np.moveaxis(images_nchw, 1, -1)
print(f"NHWC (moveaxis): {images_nhwc2.shape}")

NCHW: (32, 3, 224, 224)
NHWC (transpose): (32, 224, 224, 3)
NHWC (moveaxis): (32, 224, 224, 3)


### Exercise 2: Rotate a 2D array 90 degrees clockwise using transpose and flip

In [37]:
# Rotate this array 90 degrees clockwise without using np.rot90
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [38]:
# Solution
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original:\n{arr}")

# Clockwise 90 = transpose then flip left-right
rotated = np.fliplr(arr.T)
print(f"Rotated 90 CW (transpose + fliplr):\n{rotated}")

# Verify with rot90
rotated_check = np.rot90(arr, k=-1)
print(f"Using rot90:\n{rotated_check}")
print(f"Equal: {np.array_equal(rotated, rotated_check)}")

Original:
[[1 2 3]
 [4 5 6]]
Rotated 90 CW (transpose + fliplr):
[[4 1]
 [5 2]
 [6 3]]
Using rot90:
[[4 1]
 [5 2]
 [6 3]]
Equal: True


### Exercise 3: Create lag features for time series

In [40]:
# Given: prices = [100, 102, 105, 103, 107, 110]
# Create a feature matrix with columns: [price, lag1, lag2]
prices = np.array([100, 102, 105, 103, 107, 110])


In [41]:
# Solution
prices = np.array([100, 102, 105, 103, 107, 110])

# Create lags
lag1 = np.roll(prices, 1).astype(float)
lag1[0] = np.nan

lag2 = np.roll(prices, 2).astype(float)
lag2[:2] = np.nan

# Stack as feature matrix
features = np.column_stack([prices, lag1, lag2])
print(f"Feature matrix (price, lag1, lag2):\n{features}")

Feature matrix (price, lag1, lag2):
[[100.  nan  nan]
 [102. 100.  nan]
 [105. 102. 100.]
 [103. 105. 102.]
 [107. 103. 105.]
 [110. 107. 103.]]


---
## Module 02 Complete!

You have mastered Array Manipulation:
- Reshape and Resize
- Concatenate and Split
- Stacking and Tiling
- Transposing and Swapping

**Next Module:** 03_mathematical_operations - Arithmetic, statistics, linear algebra, and more!