# Introduction to NumPy

**Module 01 | Notebook 01**

---

## Objective
By the end of this notebook, you will understand:
- What NumPy is and why it is essential for scientific computing
- The difference between Python lists and NumPy arrays
- How to install and import NumPy
- Basic array creation and operations
- Performance advantages of NumPy over native Python

---
## 1. Theory: What is NumPy?

**NumPy (Numerical Python)** is the fundamental package for numerical computing in Python.

### Key Features:
1. **ndarray**: A powerful N-dimensional array object
2. **Broadcasting**: Sophisticated functions for operations on arrays
3. **Linear Algebra**: Tools for integrating C/C++ and Fortran code
4. **Performance**: Optimized for speed with pre-compiled C code

### Why NumPy over Python Lists?

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Speed | Slow (interpreted) | Fast (compiled C) |
| Memory | More overhead | Contiguous memory, efficient |
| Functionality | Basic operations | Rich mathematical operations |
| Homogeneity | Can mix types | Single data type (faster) |
| Broadcasting | Not supported | Supported |

---
## 2. Installation and Import

In [2]:
# Installation (run in terminal if not installed)
# pip install numpy

# Standard import convention - ALWAYS use 'np' alias
import numpy as np

# Check version
print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.3.5


---
## 3. Python List vs NumPy Array: A Comparison

In [3]:
# Creating a Python list
python_list = [1, 2, 3, 4, 5]
print(f"Python List: {python_list}")
print(f"Type: {type(python_list)}")

Python List: [1, 2, 3, 4, 5]
Type: <class 'list'>


In [4]:
# Creating a NumPy array from a list
numpy_array = np.array([1, 2, 3, 4, 5])
print(f"NumPy Array: {numpy_array}")
print(f"Type: {type(numpy_array)}")

NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [5]:
# Key Difference: Element-wise operations

# Python list - concatenation, NOT addition
list_result = python_list + python_list
print(f"List + List: {list_result}")  # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# NumPy array - element-wise addition
array_result = numpy_array + numpy_array
print(f"Array + Array: {array_result}")  # [2, 4, 6, 8, 10]

List + List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array + Array: [ 2  4  6  8 10]


In [6]:
# Scalar multiplication

# Python list - replication
print(f"List * 2: {python_list * 2}")  # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# NumPy array - element-wise multiplication
print(f"Array * 2: {numpy_array * 2}")  # [2, 4, 6, 8, 10]

List * 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array * 2: [ 2  4  6  8 10]


---
## 4. Performance Comparison

In [7]:
import time

# Create large data structures
size = 1_000_000
python_list_large = list(range(size))
numpy_array_large = np.arange(size)

# Benchmark: Sum operation

# Python list
start = time.time()
sum(python_list_large)
python_time = time.time() - start

# NumPy array
start = time.time()
np.sum(numpy_array_large)
numpy_time = time.time() - start

print(f"Python list sum: {python_time:.6f} seconds")
print(f"NumPy array sum: {numpy_time:.6f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster!")

Python list sum: 0.007178 seconds
NumPy array sum: 0.000583 seconds
NumPy is 12.3x faster!


In [8]:
# Memory comparison
import sys

# Python list memory
list_memory = sys.getsizeof(python_list_large)
# Add size of each integer object
list_memory += sum(sys.getsizeof(i) for i in python_list_large[:1000]) * (size/1000)

# NumPy array memory
array_memory = numpy_array_large.nbytes

print(f"Python list memory: ~{list_memory/1024/1024:.2f} MB")
print(f"NumPy array memory: {array_memory/1024/1024:.2f} MB")
print(f"NumPy uses ~{list_memory/array_memory:.1f}x less memory!")

Python list memory: ~34.33 MB
NumPy array memory: 7.63 MB
NumPy uses ~4.5x less memory!


---
## 5. Basic NumPy Array Creation

In [9]:
# From a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1}")

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr2}")

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr3}")

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# Quick creation methods (detailed in next notebook)

print(f"Zeros: {np.zeros(5)}")
print(f"Ones: {np.ones(5)}")
print(f"Range: {np.arange(0, 10, 2)}")
print(f"Linspace: {np.linspace(0, 1, 5)}")
print(f"Random: {np.random.rand(5)}")

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [0.22373273 0.51163055 0.28358523 0.49734767 0.82764715]


---
## 6. Array Attributes

In [11]:
# Create a sample array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Array:\n{arr}")
print()

# Essential attributes
print(f"Shape (rows, cols): {arr.shape}")      # (3, 4)
print(f"Number of dimensions: {arr.ndim}")     # 2
print(f"Total elements: {arr.size}")           # 12
print(f"Data type: {arr.dtype}")               # int64 or int32
print(f"Bytes per element: {arr.itemsize}")    # 8 or 4
print(f"Total bytes: {arr.nbytes}")            # 96 or 48

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape (rows, cols): (3, 4)
Number of dimensions: 2
Total elements: 12
Data type: int64
Bytes per element: 8
Total bytes: 96


---
## 7. Basic Array Operations

In [12]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

# Arithmetic operations (element-wise)
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")
print(f"Power: {b ** 2}")
print(f"Modulo: {a % 3}")

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [ 1  4  9 16 25]
Modulo: [1 2 0 1 2]


In [13]:
# Aggregation functions
arr = np.array([10, 20, 30, 40, 50])

print(f"Sum: {arr.sum()}")
print(f"Mean: {arr.mean()}")
print(f"Std Dev: {arr.std()}")
print(f"Min: {arr.min()}")
print(f"Max: {arr.max()}")
print(f"Argmin (index of min): {arr.argmin()}")
print(f"Argmax (index of max): {arr.argmax()}")

Sum: 150
Mean: 30.0
Std Dev: 14.142135623730951
Min: 10
Max: 50
Argmin (index of min): 0
Argmax (index of max): 4


---
## Key Points Summary

1. **NumPy** is the core library for numerical computing in Python
2. **ndarray** is a fixed-size, homogeneous, multidimensional array
3. NumPy is **10-100x faster** than Python lists for numerical operations
4. NumPy uses **less memory** due to contiguous storage and fixed dtypes
5. Always import as `import numpy as np` (convention)
6. Key attributes: `shape`, `ndim`, `size`, `dtype`, `nbytes`
7. Operations are **element-wise** by default (unlike Python lists)

---
## Interview Tips

**Q1: Why is NumPy faster than Python lists?**
> - Contiguous memory allocation
> - Homogeneous data types (no type checking overhead)
> - Vectorized operations implemented in C
> - Avoids Python's interpreter overhead

**Q2: What is the difference between `np.array()` and `np.asarray()`?**
> - `np.array()` always creates a copy
> - `np.asarray()` returns a view if input is already an ndarray (no copy)

**Q3: Can NumPy arrays have mixed data types?**
> No, NumPy arrays are homogeneous. If you pass mixed types, NumPy will upcast to the most general type (e.g., int to float, or everything to string).

**Q4: What is the time complexity of accessing an element in NumPy?**
> O(1) - constant time due to contiguous memory and fixed-size elements.

---
## Practice Exercises

### Exercise 1: Create and Inspect
Create a 3x4 array of integers from 1 to 12 and print all its attributes.

In [14]:
# Your code here


In [15]:
# Solution
arr = np.arange(1, 13).reshape(3, 4)
print(f"Array:\n{arr}")
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Dtype: {arr.dtype}")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Dtype: int64


### Exercise 2: Performance Test
Write code to compare the time taken to compute the dot product of two lists/arrays of 1 million elements.

In [16]:
# Your code here


In [17]:
# Solution
import time

size = 1_000_000
list_a = list(range(size))
list_b = list(range(size))
arr_a = np.arange(size)
arr_b = np.arange(size)

# Python dot product
start = time.time()
dot_list = sum(a*b for a, b in zip(list_a, list_b))
python_time = time.time() - start

# NumPy dot product
start = time.time()
dot_numpy = np.dot(arr_a, arr_b)
numpy_time = time.time() - start

print(f"Python dot product time: {python_time:.4f}s")
print(f"NumPy dot product time: {numpy_time:.6f}s")
print(f"NumPy is {python_time/numpy_time:.0f}x faster!")

Python dot product time: 0.0927s
NumPy dot product time: 0.000845s
NumPy is 110x faster!


### Exercise 3: Type Upcasting
Create an array with mixed integer and float values. What dtype does it have? Why?

In [18]:
# Your code here


In [19]:
# Solution
mixed = np.array([1, 2, 3.5, 4])
print(f"Array: {mixed}")
print(f"Dtype: {mixed.dtype}")
# Answer: float64 - NumPy upcasts to accommodate all values without data loss

Array: [1.  2.  3.5 4. ]
Dtype: float64


---
## Next Notebook
**02_array_creation.ipynb** - Deep dive into all array creation methods: zeros, ones, empty, full, arange, linspace, random, and more.