# Array Creation Methods in NumPy

**Module 01 | Notebook 02**

---

## Objective
By the end of this notebook, you will master:
- All primary array creation functions
- Creating arrays with specific patterns (zeros, ones, identity)
- Generating ranges and sequences
- Random array generation
- Creating arrays from existing data

In [2]:
import numpy as np
np.set_printoptions(precision=3)  # Cleaner output

---
## 1. From Python Sequences

In [3]:
# From a list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"From list: {arr1}")

# From a tuple
arr2 = np.array((10, 20, 30))
print(f"From tuple: {arr2}")

# From nested lists (2D array)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{arr3}")

From list: [1 2 3 4 5]
From tuple: [10 20 30]
2D array:
[[1 2 3]
 [4 5 6]]


In [4]:
# Specifying dtype during creation
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_complex = np.array([1, 2, 3], dtype=np.complex128)

print(f"int32: {arr_int}, dtype: {arr_int.dtype}")
print(f"float64: {arr_float}, dtype: {arr_float.dtype}")
print(f"complex: {arr_complex}, dtype: {arr_complex.dtype}")

int32: [1 2 3], dtype: int32
float64: [1. 2. 3.], dtype: float64
complex: [1.+0.j 2.+0.j 3.+0.j], dtype: complex128


### np.array() vs np.asarray()

In [5]:
# np.array() ALWAYS creates a copy
original = np.array([1, 2, 3])
copy_arr = np.array(original)
copy_arr[0] = 999
print(f"Original after np.array modification: {original}")  # Unchanged

# np.asarray() returns a view if input is already ndarray
original = np.array([1, 2, 3])
view_arr = np.asarray(original)
view_arr[0] = 999
print(f"Original after np.asarray modification: {original}")  # Changed!

Original after np.array modification: [1 2 3]
Original after np.asarray modification: [999   2   3]


---
## 2. Zeros, Ones, and Empty Arrays

In [6]:
# np.zeros - all elements are 0
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4))  # Note: shape as tuple
zeros_3d = np.zeros((2, 3, 4))

print(f"1D zeros: {zeros_1d}")
print(f"2D zeros shape: {zeros_2d.shape}")
print(f"3D zeros shape: {zeros_3d.shape}")

1D zeros: [0. 0. 0. 0. 0.]
2D zeros shape: (3, 4)
3D zeros shape: (2, 3, 4)


In [7]:
# np.ones - all elements are 1
ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))

print(f"1D ones: {ones_1d}")
print(f"2D ones:\n{ones_2d}")

1D ones: [1. 1. 1. 1. 1.]
2D ones:
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# np.empty - uninitialized (faster, but contains garbage values)
# WARNING: Only use when you will fill all values immediately
empty_arr = np.empty((2, 3))
print(f"Empty array (garbage values):\n{empty_arr}")

Empty array (garbage values):
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# np.full - fill with a specific value
full_arr = np.full((3, 3), 7)
print(f"Full array (all 7s):\n{full_arr}")

# With float fill value
full_float = np.full((2, 4), 3.14)
print(f"Full float array:\n{full_float}")

Full array (all 7s):
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Full float array:
[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


---
## 3. Creating Arrays Like Existing Arrays

In [10]:
# Create a reference array
reference = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Reference array:\n{reference}")
print(f"Reference shape: {reference.shape}, dtype: {reference.dtype}")

Reference array:
[[1 2 3]
 [4 5 6]]
Reference shape: (2, 3), dtype: int64


In [11]:
# zeros_like, ones_like, empty_like, full_like
# These create arrays with same shape and dtype as the reference

zeros_like_ref = np.zeros_like(reference)
ones_like_ref = np.ones_like(reference)
full_like_ref = np.full_like(reference, 99)

print(f"zeros_like:\n{zeros_like_ref}")
print(f"ones_like:\n{ones_like_ref}")
print(f"full_like (99):\n{full_like_ref}")

zeros_like:
[[0 0 0]
 [0 0 0]]
ones_like:
[[1 1 1]
 [1 1 1]]
full_like (99):
[[99 99 99]
 [99 99 99]]


---
## 4. Identity and Diagonal Matrices

In [12]:
# np.eye - Identity matrix (1s on diagonal, 0s elsewhere)
identity_3 = np.eye(3)
print(f"3x3 Identity:\n{identity_3}")

# Rectangular identity
eye_rect = np.eye(3, 5)  # 3 rows, 5 columns
print(f"3x5 Eye:\n{eye_rect}")

# Offset diagonal with k parameter
eye_upper = np.eye(4, k=1)  # Upper diagonal
eye_lower = np.eye(4, k=-1)  # Lower diagonal
print(f"Upper diagonal (k=1):\n{eye_upper}")
print(f"Lower diagonal (k=-1):\n{eye_lower}")

3x3 Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3x5 Eye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
Upper diagonal (k=1):
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
Lower diagonal (k=-1):
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [13]:
# np.identity - strictly square identity matrix
identity = np.identity(4)
print(f"4x4 Identity:\n{identity}")

4x4 Identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# np.diag - create diagonal matrix or extract diagonal

# Create diagonal matrix from 1D array
diag_matrix = np.diag([1, 2, 3, 4])
print(f"Diagonal matrix:\n{diag_matrix}")

# Extract diagonal from 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diag(matrix)
print(f"Extracted diagonal: {diagonal}")

# Extract off-diagonals
upper_diag = np.diag(matrix, k=1)
lower_diag = np.diag(matrix, k=-1)
print(f"Upper diagonal (k=1): {upper_diag}")
print(f"Lower diagonal (k=-1): {lower_diag}")

Diagonal matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Extracted diagonal: [1 5 9]
Upper diagonal (k=1): [2 6]
Lower diagonal (k=-1): [4 8]


---
## 5. Ranges and Sequences

### np.arange - Like Python's range(), but returns array

In [15]:
# Syntax: np.arange(start, stop, step)
# Note: stop is EXCLUSIVE (not included)

# Single argument - 0 to n-1
arr1 = np.arange(10)
print(f"arange(10): {arr1}")

# Two arguments - start to stop-1
arr2 = np.arange(5, 15)
print(f"arange(5, 15): {arr2}")

# Three arguments - with step
arr3 = np.arange(0, 20, 2)
print(f"arange(0, 20, 2): {arr3}")

# Negative step (reverse)
arr4 = np.arange(10, 0, -1)
print(f"arange(10, 0, -1): {arr4}")

# Float step
arr5 = np.arange(0, 1, 0.1)
print(f"arange(0, 1, 0.1): {arr5}")

arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]
arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18]
arange(10, 0, -1): [10  9  8  7  6  5  4  3  2  1]
arange(0, 1, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### np.linspace - Evenly spaced numbers over interval

In [16]:
# Syntax: np.linspace(start, stop, num)
# Note: stop is INCLUSIVE by default

# 5 evenly spaced points from 0 to 10
lin1 = np.linspace(0, 10, 5)
print(f"linspace(0, 10, 5): {lin1}")

# 11 points from 0 to 1
lin2 = np.linspace(0, 1, 11)
print(f"linspace(0, 1, 11): {lin2}")

# Exclude endpoint
lin3 = np.linspace(0, 10, 5, endpoint=False)
print(f"linspace(0, 10, 5, endpoint=False): {lin3}")

# Return step size with retstep=True
lin4, step = np.linspace(0, 10, 5, retstep=True)
print(f"linspace values: {lin4}, step size: {step}")

linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
linspace(0, 1, 11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
linspace(0, 10, 5, endpoint=False): [0. 2. 4. 6. 8.]
linspace values: [ 0.   2.5  5.   7.5 10. ], step size: 2.5


### np.logspace - Evenly spaced on log scale

In [17]:
# Syntax: np.logspace(start, stop, num, base=10)
# Returns base^start to base^stop

# 5 points from 10^0 to 10^4 (1 to 10000)
log1 = np.logspace(0, 4, 5)
print(f"logspace(0, 4, 5): {log1}")

# Using base 2
log2 = np.logspace(0, 8, 9, base=2)
print(f"logspace base 2: {log2}")

logspace(0, 4, 5): [1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
logspace base 2: [  1.   2.   4.   8.  16.  32.  64. 128. 256.]


### np.geomspace - Geometric spacing

In [18]:
# Syntax: np.geomspace(start, stop, num)
# Start and stop are actual values (not exponents)

geo = np.geomspace(1, 1000, 4)
print(f"geomspace(1, 1000, 4): {geo}")
# Each value is previous * constant ratio

geomspace(1, 1000, 4): [   1.   10.  100. 1000.]


---
## 6. Random Array Generation

In [19]:
# Set seed for reproducibility
np.random.seed(42)

In [20]:
# Uniform distribution [0, 1)
rand_uniform = np.random.rand(3, 4)
print(f"Uniform [0,1):\n{rand_uniform}")

Uniform [0,1):
[[0.375 0.951 0.732 0.599]
 [0.156 0.156 0.058 0.866]
 [0.601 0.708 0.021 0.97 ]]


In [21]:
# Standard normal distribution (mean=0, std=1)
rand_normal = np.random.randn(3, 4)
print(f"Standard normal:\n{rand_normal}")

Standard normal:
[[-0.469  0.543 -0.463 -0.466]
 [ 0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412]]


In [22]:
# Random integers
rand_int = np.random.randint(0, 10, size=(3, 4))  # [0, 10)
print(f"Random integers [0, 10):\n{rand_int}")

# Single random integer
single_int = np.random.randint(1, 100)
print(f"Single random int [1, 100): {single_int}")

Random integers [0, 10):
[[2 6 3 8]
 [2 4 2 6]
 [4 8 6 1]]
Single random int [1, 100): 4


In [23]:
# Random floats in a range
rand_range = np.random.uniform(low=5, high=10, size=(2, 3))
print(f"Uniform [5, 10):\n{rand_range}")

Uniform [5, 10):
[[9.711 7.816 6.927]
 [5.08  6.154 6.205]]


In [24]:
# Normal distribution with custom mean and std
rand_normal_custom = np.random.normal(loc=100, scale=15, size=(2, 3))
print(f"Normal (mean=100, std=15):\n{rand_normal_custom}")

Normal (mean=100, std=15):
[[114.233 123.713  94.477]
 [105.633  82.103  93.864]]


In [25]:
# Random choice from array
choices = np.array(['apple', 'banana', 'cherry', 'date'])
random_picks = np.random.choice(choices, size=6)
print(f"Random choices: {random_picks}")

# Without replacement
unique_picks = np.random.choice(choices, size=3, replace=False)
print(f"Unique choices: {unique_picks}")

Random choices: ['date' 'banana' 'banana' 'banana' 'banana' 'banana']
Unique choices: ['cherry' 'apple' 'banana']


In [26]:
# Shuffle array in-place
arr = np.arange(10)
np.random.shuffle(arr)
print(f"Shuffled: {arr}")

# Permutation (returns new shuffled array)
perm = np.random.permutation(10)
print(f"Permutation: {perm}")

Shuffled: [4 2 7 0 6 3 5 8 9 1]
Permutation: [5 2 7 3 0 8 9 6 1 4]


### Modern Random Generator (NumPy 1.17+)

In [27]:
# Recommended approach for new code
rng = np.random.default_rng(seed=42)

print(f"Random floats: {rng.random(5)}")
print(f"Random integers: {rng.integers(0, 10, size=5)}")
print(f"Normal: {rng.normal(0, 1, size=5)}")

Random floats: [0.774 0.439 0.859 0.697 0.094]
Random integers: [5 9 7 7 7]
Normal: [-0.017 -0.853  0.879  0.778  0.066]


---
## 7. Special Arrays

In [28]:
# np.tile - repeat array like tiles
arr = np.array([1, 2, 3])
tiled = np.tile(arr, 3)
print(f"tile([1,2,3], 3): {tiled}")

# 2D tiling
tiled_2d = np.tile(arr, (2, 3))
print(f"tile([1,2,3], (2,3)):\n{tiled_2d}")

tile([1,2,3], 3): [1 2 3 1 2 3 1 2 3]
tile([1,2,3], (2,3)):
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [29]:
# np.repeat - repeat each element
arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(f"repeat([1,2,3], 3): {repeated}")

# Different repeat counts per element
varied_repeat = np.repeat(arr, [1, 2, 3])
print(f"repeat([1,2,3], [1,2,3]): {varied_repeat}")

repeat([1,2,3], 3): [1 1 1 2 2 2 3 3 3]
repeat([1,2,3], [1,2,3]): [1 2 2 3 3 3]


In [30]:
# np.meshgrid - coordinate matrices from vectors
x = np.array([1, 2, 3])
y = np.array([10, 20])

xx, yy = np.meshgrid(x, y)
print(f"X grid:\n{xx}")
print(f"Y grid:\n{yy}")

# Useful for creating coordinate grids for plots

X grid:
[[1 2 3]
 [1 2 3]]
Y grid:
[[10 10 10]
 [20 20 20]]


In [31]:
# np.fromfunction - create array using function
def create_element(i, j):
    return i + j

func_arr = np.fromfunction(create_element, (3, 4), dtype=int)
print(f"fromfunction (i+j):\n{func_arr}")

# Multiplication table
mult_table = np.fromfunction(lambda i, j: (i+1) * (j+1), (5, 5), dtype=int)
print(f"Multiplication table:\n{mult_table}")

fromfunction (i+j):
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
Multiplication table:
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


---
## Key Points Summary

| Function | Purpose | Example |
|----------|---------|--------|
| `np.array()` | Create from sequence (always copies) | `np.array([1,2,3])` |
| `np.asarray()` | Create from sequence (view if ndarray) | `np.asarray(arr)` |
| `np.zeros()` | Array of zeros | `np.zeros((3,4))` |
| `np.ones()` | Array of ones | `np.ones((3,4))` |
| `np.empty()` | Uninitialized array | `np.empty((3,4))` |
| `np.full()` | Array of specific value | `np.full((3,4), 7)` |
| `np.eye()` | Identity/diagonal matrix | `np.eye(4)` |
| `np.diag()` | Create or extract diagonal | `np.diag([1,2,3])` |
| `np.arange()` | Range (exclusive stop) | `np.arange(0,10,2)` |
| `np.linspace()` | Linear spacing (inclusive) | `np.linspace(0,1,11)` |
| `np.logspace()` | Log spacing | `np.logspace(0,4,5)` |
| `np.random.rand()` | Uniform [0,1) | `np.random.rand(3,4)` |
| `np.random.randn()` | Standard normal | `np.random.randn(3,4)` |
| `np.random.randint()` | Random integers | `np.random.randint(0,10,(3,4))` |

---
## Interview Tips

**Q1: What is the difference between np.arange() and np.linspace()?**
> - `arange(start, stop, step)`: Uses step size, stop is exclusive
> - `linspace(start, stop, num)`: Uses number of points, stop is inclusive by default
> - Use `linspace` when you need exact number of points
> - Use `arange` when step size matters

**Q2: Why might np.arange() produce unexpected results with floats?**
> Due to floating-point precision issues. For example, `np.arange(0, 1, 0.1)` might give 10 or 11 elements depending on rounding. Prefer `linspace` for float ranges.

**Q3: What is the difference between np.empty() and np.zeros()?**
> - `empty()` allocates memory but doesn't initialize (faster, garbage values)
> - `zeros()` allocates and initializes all elements to 0 (slower, predictable)
> - Use `empty()` only when you will immediately fill all values

**Q4: How do you ensure reproducible random arrays?**
> Set the seed: `np.random.seed(42)` or better, use `rng = np.random.default_rng(42)`

---
## Practice Exercises

### Exercise 1: Create a 5x5 matrix with 1s on the border and 0s inside

In [32]:
# Your code here


In [33]:
# Solution
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print(border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Exercise 2: Create an 8x8 checkerboard pattern (alternating 0s and 1s)

In [34]:
# Your code here


In [35]:
# Solution
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Exercise 3: Create an array of 10 random numbers between 50 and 100

In [36]:
# Your code here


In [37]:
# Solution
# Method 1: Using uniform
random_floats = np.random.uniform(50, 100, 10)
print(f"Floats: {random_floats}")

# Method 2: Using randint for integers
random_ints = np.random.randint(50, 101, 10)  # 101 because exclusive
print(f"Ints: {random_ints}")

Floats: [64.814 58.263 50.782 71.17  69.744 64.674 50.704 59.942 85.567 89.509]
Ints: [54 91 88 90 77 56 58 57 61 83]


### Exercise 4: Create a 3x3 matrix with values 0-8 using arange and reshape

In [38]:
# Your code here


In [39]:
# Solution
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Exercise 5: Create a 5x5 matrix with row values ranging from 0 to 4

In [40]:
# Your code here


In [41]:
# Solution
# Method 1: Using tile
row_matrix = np.tile(np.arange(5), (5, 1))
print(row_matrix)

# Method 2: Using broadcasting (covered later)
# row_matrix = np.zeros((5,5)) + np.arange(5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


---
## Next Notebook
**03_array_attributes_and_dtypes.ipynb** - Deep dive into array attributes, data types, and type conversions.