# Indexing and Slicing

**Module 01 | Notebook 04**

---

## Objective
By the end of this notebook, you will master:
- Basic indexing for 1D, 2D, and ND arrays
- Slicing with start:stop:step syntax
- Negative indexing
- Views vs copies
- Common indexing patterns and pitfalls

In [2]:
import numpy as np
np.set_printoptions(precision=2)

---
## 1. Basic Indexing (1D Arrays)

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(f"Array: {arr}")
print(f"Length: {len(arr)}")

Array: [10 20 30 40 50 60 70 80 90]
Length: 9


In [4]:
# Positive indexing (0-based)
print(f"First element (index 0): {arr[0]}")
print(f"Third element (index 2): {arr[2]}")
print(f"Last by index (index 8): {arr[8]}")

First element (index 0): 10
Third element (index 2): 30
Last by index (index 8): 90


In [5]:
# Negative indexing (from the end)
print(f"Last element (index -1): {arr[-1]}")
print(f"Second to last (index -2): {arr[-2]}")
print(f"First element (index -9): {arr[-9]}")

Last element (index -1): 90
Second to last (index -2): 80
First element (index -9): 10


In [6]:
# Index visualization
# Positive:  0   1   2   3   4   5   6   7   8
# Array:    10  20  30  40  50  60  70  80  90
# Negative: -9  -8  -7  -6  -5  -4  -3  -2  -1

---
## 2. Basic Slicing (1D Arrays)

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Syntax: arr[start:stop:step]
# - start: inclusive (default 0)
# - stop: exclusive (default len)
# - step: increment (default 1)

In [8]:
# Basic slicing
print(f"arr[2:5]: {arr[2:5]}")      # Elements at index 2, 3, 4
print(f"arr[:4]: {arr[:4]}")        # First 4 elements (0, 1, 2, 3)
print(f"arr[5:]: {arr[5:]}")        # From index 5 to end
print(f"arr[:]: {arr[:]}")          # All elements (shallow copy)

arr[2:5]: [30 40 50]
arr[:4]: [10 20 30 40]
arr[5:]: [60 70 80 90]
arr[:]: [10 20 30 40 50 60 70 80 90]


In [9]:
# With step
print(f"arr[::2]: {arr[::2]}")      # Every 2nd element
print(f"arr[1::2]: {arr[1::2]}")    # Every 2nd, starting at 1
print(f"arr[::3]: {arr[::3]}")      # Every 3rd element

arr[::2]: [10 30 50 70 90]
arr[1::2]: [20 40 60 80]
arr[::3]: [10 40 70]


In [10]:
# Negative step (reverse)
print(f"arr[::-1]: {arr[::-1]}")    # Reverse entire array
print(f"arr[::-2]: {arr[::-2]}")    # Reverse, every 2nd
print(f"arr[7:2:-1]: {arr[7:2:-1]}")  # Reverse slice

arr[::-1]: [90 80 70 60 50 40 30 20 10]
arr[::-2]: [90 70 50 30 10]
arr[7:2:-1]: [80 70 60 50 40]


In [11]:
# Negative indices in slicing
print(f"arr[-3:]: {arr[-3:]}")      # Last 3 elements
print(f"arr[:-3]: {arr[:-3]}")      # All except last 3
print(f"arr[-5:-2]: {arr[-5:-2]}")  # Elements -5, -4, -3

arr[-3:]: [70 80 90]
arr[:-3]: [10 20 30 40 50 60]
arr[-5:-2]: [50 60 70]


---
## 3. 2D Array Indexing

In [12]:
# Create a 2D array
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(f"2D Array:\n{arr2d}")
print(f"Shape: {arr2d.shape}")

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)


In [13]:
# Single element access: arr[row, col]
print(f"arr2d[0, 0]: {arr2d[0, 0]}")    # Top-left: 1
print(f"arr2d[1, 2]: {arr2d[1, 2]}")    # Row 1, Col 2: 7
print(f"arr2d[-1, -1]: {arr2d[-1, -1]}")  # Bottom-right: 16

arr2d[0, 0]: 1
arr2d[1, 2]: 7
arr2d[-1, -1]: 16


In [14]:
# Equivalent syntax (but less efficient)
print(f"arr2d[1][2]: {arr2d[1][2]}")  # Same as arr2d[1, 2]

arr2d[1][2]: 7


In [15]:
# Row selection
print(f"Row 0: {arr2d[0]}")      # First row
print(f"Row 2: {arr2d[2]}")      # Third row
print(f"Last row: {arr2d[-1]}")  # Last row

Row 0: [1 2 3 4]
Row 2: [ 9 10 11 12]
Last row: [13 14 15 16]


In [16]:
# Column selection (requires slicing)
print(f"Col 0: {arr2d[:, 0]}")     # First column
print(f"Col 2: {arr2d[:, 2]}")     # Third column
print(f"Last col: {arr2d[:, -1]}")  # Last column

Col 0: [ 1  5  9 13]
Col 2: [ 3  7 11 15]
Last col: [ 4  8 12 16]


---
## 4. 2D Array Slicing

In [17]:
arr2d = np.arange(1, 17).reshape(4, 4)
print(f"Array:\n{arr2d}")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
# Subarray extraction: arr[row_slice, col_slice]

# Top-left 2x2
print(f"Top-left 2x2:\n{arr2d[:2, :2]}")

# Bottom-right 2x2
print(f"Bottom-right 2x2:\n{arr2d[2:, 2:]}")

# Middle 2x2
print(f"Middle 2x2:\n{arr2d[1:3, 1:3]}")

Top-left 2x2:
[[1 2]
 [5 6]]
Bottom-right 2x2:
[[11 12]
 [15 16]]
Middle 2x2:
[[ 6  7]
 [10 11]]


In [19]:
# Row slicing
print(f"First 2 rows:\n{arr2d[:2]}")
print(f"Last 2 rows:\n{arr2d[-2:]}")
print(f"Every other row:\n{arr2d[::2]}")

First 2 rows:
[[1 2 3 4]
 [5 6 7 8]]
Last 2 rows:
[[ 9 10 11 12]
 [13 14 15 16]]
Every other row:
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [20]:
# Column slicing
print(f"First 2 cols:\n{arr2d[:, :2]}")
print(f"Every other col:\n{arr2d[:, ::2]}")

First 2 cols:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Every other col:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [21]:
# Combined row and column slicing
print(f"Rows 1-2, Cols 1-3:\n{arr2d[1:3, 1:4]}")
print(f"Every other element:\n{arr2d[::2, ::2]}")

Rows 1-2, Cols 1-3:
[[ 6  7  8]
 [10 11 12]]
Every other element:
[[ 1  3]
 [ 9 11]]


---
## 5. 3D and ND Indexing

In [22]:
# 3D array (2 blocks of 3x4 matrices)
arr3d = np.arange(24).reshape(2, 3, 4)
print(f"3D Array (shape {arr3d.shape}):\n{arr3d}")

3D Array (shape (2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
# Access single element: arr[block, row, col]
print(f"arr3d[0, 1, 2]: {arr3d[0, 1, 2]}")  # Block 0, Row 1, Col 2: 6

arr3d[0, 1, 2]: 6


In [24]:
# Access a 2D slice (one block)
print(f"First block:\n{arr3d[0]}")
print(f"Second block:\n{arr3d[1]}")

First block:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Second block:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [25]:
# Access a 1D slice (one row from one block)
print(f"Block 1, Row 2: {arr3d[1, 2]}")

Block 1, Row 2: [20 21 22 23]


In [26]:
# Using ellipsis (...) to represent multiple colons
# arr3d[..., 0] is equivalent to arr3d[:, :, 0]

print(f"First column of all blocks:\n{arr3d[..., 0]}")
print(f"All columns of first row:\n{arr3d[:, 0, :]}")

First column of all blocks:
[[ 0  4  8]
 [12 16 20]]
All columns of first row:
[[ 0  1  2  3]
 [12 13 14 15]]


---
## 6. Views vs Copies

### Critical Concept: Slicing returns a VIEW, not a copy!

In [27]:
# Slicing creates a VIEW
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]

print(f"Original: {original}")
print(f"View: {view}")

# Modifying view affects original!
view[0] = 999
print(f"After modifying view[0] = 999:")
print(f"Original: {original}")  # [1, 999, 3, 4, 5]
print(f"View: {view}")          # [999, 3, 4]

Original: [1 2 3 4 5]
View: [2 3 4]
After modifying view[0] = 999:
Original: [  1 999   3   4   5]
View: [999   3   4]


In [28]:
# Check if array is a view
print(f"View's base is original? {view.base is original}")
print(f"Shares memory? {np.shares_memory(original, view)}")

View's base is original? True
Shares memory? True


In [29]:
# Creating a true COPY
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()  # Explicit copy

copy[0] = 999
print(f"Original (unchanged): {original}")
print(f"Copy (modified): {copy}")

Original (unchanged): [1 2 3 4 5]
Copy (modified): [999   3   4]


In [30]:
# 2D view example
arr2d = np.arange(12).reshape(3, 4)
print(f"Original:\n{arr2d}")

row_view = arr2d[1]  # View of row 1
row_view[0] = 999
print(f"After modifying row view:\n{arr2d}")

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After modifying row view:
[[  0   1   2   3]
 [999   5   6   7]
 [  8   9  10  11]]


---
## 7. Modifying Array Values with Indexing

In [31]:
arr = np.arange(10)
print(f"Original: {arr}")

# Single element
arr[0] = 100
print(f"After arr[0] = 100: {arr}")

# Slice assignment (broadcasts single value)
arr[5:8] = 0
print(f"After arr[5:8] = 0: {arr}")

# Slice assignment with array
arr[1:4] = [10, 20, 30]
print(f"After arr[1:4] = [10,20,30]: {arr}")

Original: [0 1 2 3 4 5 6 7 8 9]
After arr[0] = 100: [100   1   2   3   4   5   6   7   8   9]
After arr[5:8] = 0: [100   1   2   3   4   0   0   0   8   9]
After arr[1:4] = [10,20,30]: [100  10  20  30   4   0   0   0   8   9]


In [32]:
# 2D modifications
arr2d = np.zeros((4, 4), dtype=int)
print(f"Original:\n{arr2d}")

# Set entire row
arr2d[0] = 1
print(f"After setting row 0:\n{arr2d}")

# Set entire column
arr2d[:, -1] = 9
print(f"After setting last column:\n{arr2d}")

# Set subarray
arr2d[1:3, 1:3] = 5
print(f"After setting middle 2x2:\n{arr2d}")

Original:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
After setting row 0:
[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
After setting last column:
[[1 1 1 9]
 [0 0 0 9]
 [0 0 0 9]
 [0 0 0 9]]
After setting middle 2x2:
[[1 1 1 9]
 [0 5 5 9]
 [0 5 5 9]
 [0 0 0 9]]


---
## 8. Common Indexing Patterns

In [33]:
arr = np.arange(1, 11)
print(f"Array: {arr}")

# First N elements
n = 3
print(f"First {n}: {arr[:n]}")

# Last N elements
print(f"Last {n}: {arr[-n:]}")

# Remove first and last
print(f"Without first and last: {arr[1:-1]}")

# Every Nth element
print(f"Every 3rd: {arr[::3]}")

# Reverse
print(f"Reversed: {arr[::-1]}")

Array: [ 1  2  3  4  5  6  7  8  9 10]
First 3: [1 2 3]
Last 3: [ 8  9 10]
Without first and last: [2 3 4 5 6 7 8 9]
Every 3rd: [ 1  4  7 10]
Reversed: [10  9  8  7  6  5  4  3  2  1]


In [34]:
# 2D patterns
arr2d = np.arange(16).reshape(4, 4)
print(f"Array:\n{arr2d}")

# Main diagonal (using np.diag is better, but possible with indexing)
print(f"Diagonal: {np.diag(arr2d)}")

# Anti-diagonal
print(f"Anti-diagonal: {np.diag(arr2d[:, ::-1])}")

# Border elements (indirect - need fancy indexing for direct)
top = arr2d[0, :]
bottom = arr2d[-1, :]
left = arr2d[1:-1, 0]
right = arr2d[1:-1, -1]
border = np.concatenate([top, right, bottom[::-1], left[::-1]])
print(f"Border (clockwise): {border}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal: [ 0  5 10 15]
Anti-diagonal: [ 3  6  9 12]
Border (clockwise): [ 0  1  2  3  7 11 15 14 13 12  8  4]


---
## 9. Newaxis and Dimension Expansion

In [35]:
arr = np.array([1, 2, 3, 4])
print(f"Original: {arr}, shape: {arr.shape}")

# Add axis at position 0 (row vector to column-ish)
row = arr[np.newaxis, :]
print(f"Row vector: {row}, shape: {row.shape}")

# Add axis at position 1 (column vector)
col = arr[:, np.newaxis]
print(f"Column vector:\n{col}, shape: {col.shape}")

Original: [1 2 3 4], shape: (4,)
Row vector: [[1 2 3 4]], shape: (1, 4)
Column vector:
[[1]
 [2]
 [3]
 [4]], shape: (4, 1)


In [36]:
# Using None (equivalent to np.newaxis)
col_alt = arr[:, None]
print(f"Using None: shape {col_alt.shape}")

# Useful for broadcasting
a = np.array([1, 2, 3])
b = np.array([10, 20])

# Outer product using broadcasting
outer = a[:, np.newaxis] * b[np.newaxis, :]
print(f"Outer product:\n{outer}")

Using None: shape (4, 1)
Outer product:
[[10 20]
 [20 40]
 [30 60]]


---
## Key Points Summary

**Indexing Basics:**
- 0-based indexing (first element is index 0)
- Negative indices count from end (-1 is last)
- Multi-dimensional: `arr[row, col]` or `arr[dim0, dim1, dim2]`

**Slicing Syntax:** `arr[start:stop:step]`
- `start` is inclusive (default: 0)
- `stop` is exclusive (default: len)
- `step` is increment (default: 1, negative for reverse)

**Views vs Copies:**
- Slicing returns a VIEW (shares memory)
- Modifying view modifies original!
- Use `.copy()` for independent copy

**Special Syntax:**
- `...` (ellipsis): shorthand for multiple `:`
- `np.newaxis` or `None`: add new dimension

---
## Interview Tips

**Q1: What is the difference between arr[1:3] and arr[[1, 2]]?**
> - `arr[1:3]` is basic slicing, returns a VIEW
> - `arr[[1, 2]]` is fancy indexing, returns a COPY
> - Views share memory, copies don't

**Q2: How do you extract the diagonal of a 2D array?**
> Use `np.diag(arr)` or with indexing: `arr[range(n), range(n)]`

**Q3: Why doesn't modifying a slice in Python lists affect the original?**
> Python lists slice operation creates a new list (shallow copy).
> NumPy returns a view for efficiency. This is a key difference!

**Q4: How do you reverse a 2D array along both axes?**
> `arr[::-1, ::-1]` - reverses rows and columns simultaneously

---
## Practice Exercises

### Exercise 1: Extract elements
Given array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], extract:
- Elements at odd indices
- Every third element starting from index 1
- Last 4 elements in reverse

In [37]:
# Your code here
arr = np.arange(10)


In [38]:
# Solution
arr = np.arange(10)
print(f"Array: {arr}")
print(f"Odd indices: {arr[1::2]}")
print(f"Every 3rd from index 1: {arr[1::3]}")
print(f"Last 4 reversed: {arr[-1:-5:-1]}")
# or: arr[-4:][::-1]

Array: [0 1 2 3 4 5 6 7 8 9]
Odd indices: [1 3 5 7 9]
Every 3rd from index 1: [1 4 7]
Last 4 reversed: [9 8 7 6]


### Exercise 2: 2D extraction
Create a 5x5 array with values 1-25. Extract:
- The center 3x3 subarray
- The four corners as a 1D array
- Every other row and column (checkerboard pattern)

In [39]:
# Your code here


In [40]:
# Solution
arr = np.arange(1, 26).reshape(5, 5)
print(f"Array:\n{arr}")

# Center 3x3
center = arr[1:4, 1:4]
print(f"Center 3x3:\n{center}")

# Four corners
corners = np.array([arr[0, 0], arr[0, -1], arr[-1, 0], arr[-1, -1]])
print(f"Corners: {corners}")

# Checkerboard
checker = arr[::2, ::2]
print(f"Checkerboard:\n{checker}")

Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Center 3x3:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Corners: [ 1  5 21 25]
Checkerboard:
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


### Exercise 3: View or Copy?
Determine which operations return views and which return copies. Verify your answers.

In [41]:
# Your code here
arr = np.arange(10)

a = arr[2:5]        # View or Copy?
b = arr[::2]        # View or Copy?
c = arr[[1, 3, 5]]  # View or Copy?
d = arr.reshape(2, 5)  # View or Copy?


In [42]:
# Solution
arr = np.arange(10)

a = arr[2:5]        # VIEW (basic slicing)
b = arr[::2]        # VIEW (basic slicing with step)
c = arr[[1, 3, 5]]  # COPY (fancy indexing)
d = arr.reshape(2, 5)  # VIEW (if possible)

print(f"a shares memory: {np.shares_memory(arr, a)}")
print(f"b shares memory: {np.shares_memory(arr, b)}")
print(f"c shares memory: {np.shares_memory(arr, c)}")
print(f"d shares memory: {np.shares_memory(arr, d)}")

a shares memory: True
b shares memory: True
c shares memory: False
d shares memory: True


### Exercise 4: Swap first and last rows of a 2D array

In [43]:
# Your code here
arr = np.arange(12).reshape(3, 4)


In [44]:
# Solution
arr = np.arange(12).reshape(3, 4)
print(f"Before:\n{arr}")

# Method 1: Using temporary
arr[[0, -1]] = arr[[-1, 0]]
print(f"After swap:\n{arr}")

Before:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After swap:
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


---
## Module 01 Complete!

You have mastered NumPy Basics:
- Introduction to NumPy
- Array Creation Methods
- Array Attributes and Data Types
- Indexing and Slicing

**Next Module:** 02_array_manipulation - Reshape, concatenate, split, stack, and more!