# Fancy Indexing

**Module 05 | Notebook 01**

---

## Objective
By the end of this notebook, you will master:
- Integer array indexing
- Multi-dimensional fancy indexing
- Combining fancy and basic indexing
- Advanced selection patterns
- Fancy indexing vs views (copy behavior)

In [2]:
import numpy as np
np.set_printoptions(precision=2)

---
## 1. Integer Array Indexing (1D)

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(f"Array: {arr}")

Array: [10 20 30 40 50 60 70]


In [4]:
# Select multiple elements by index array
indices = np.array([0, 2, 4])
selected = arr[indices]
print(f"Indices: {indices}")
print(f"Selected: {selected}")

Indices: [0 2 4]
Selected: [10 30 50]


In [5]:
# Can also use list
selected = arr[[1, 3, 5]]
print(f"Using list [1,3,5]: {selected}")

Using list [1,3,5]: [20 40 60]


In [6]:
# Indices can repeat
indices = [0, 0, 1, 1, 2]
print(f"Repeated indices: {arr[indices]}")

Repeated indices: [10 10 20 20 30]


In [7]:
# Negative indices work
indices = [-1, -2, 0]
print(f"Negative indices: {arr[indices]}")

Negative indices: [70 60 10]


In [8]:
# Order matters and can rearrange
indices = [6, 4, 2, 0]
print(f"Reversed selection: {arr[indices]}")

Reversed selection: [70 50 30 10]


---
## 2. Fancy Indexing Returns COPY

In [9]:
# Key difference from slicing!
arr = np.arange(10)
print(f"Original: {arr}")

# Slicing returns VIEW
slice_view = arr[2:5]
print(f"Slice shares memory: {np.shares_memory(arr, slice_view)}")

# Fancy indexing returns COPY
fancy_copy = arr[[2, 3, 4]]
print(f"Fancy shares memory: {np.shares_memory(arr, fancy_copy)}")

Original: [0 1 2 3 4 5 6 7 8 9]
Slice shares memory: True
Fancy shares memory: False


In [10]:
# Modifying fancy index result doesn't affect original
arr = np.arange(10)
fancy = arr[[2, 3, 4]]
fancy[0] = 999

print(f"Modified fancy: {fancy}")
print(f"Original unchanged: {arr}")

Modified fancy: [999   3   4]
Original unchanged: [0 1 2 3 4 5 6 7 8 9]


In [11]:
# BUT: Assignment with fancy indexing DOES modify original
arr = np.arange(10)
arr[[2, 3, 4]] = [100, 200, 300]
print(f"Assigned via fancy: {arr}")

Assigned via fancy: [  0   1 100 200 300   5   6   7   8   9]


---
## 3. Multi-dimensional Fancy Indexing

In [12]:
arr = np.arange(12).reshape(3, 4)
print(f"Array:\n{arr}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
# Select specific rows
rows = [0, 2]
selected_rows = arr[rows]
print(f"Rows [0, 2]:\n{selected_rows}")

Rows [0, 2]:
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [14]:
# Select specific columns
cols = [1, 3]
selected_cols = arr[:, cols]
print(f"Columns [1, 3]:\n{selected_cols}")

Columns [1, 3]:
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [15]:
# Select specific elements: arr[rows, cols]
# This selects (row[i], col[i]) pairs!
rows = [0, 1, 2]
cols = [0, 2, 3]

elements = arr[rows, cols]
print(f"Elements at (0,0), (1,2), (2,3): {elements}")

Elements at (0,0), (1,2), (2,3): [ 0  6 11]


In [16]:
# Common mistake: wanting rectangular selection
# arr[[0,2], [1,3]] gives 2 elements, NOT 2x2 submatrix!

# For rectangular selection, use np.ix_
rows = [0, 2]
cols = [1, 3]

# This creates mesh of indices
submatrix = arr[np.ix_(rows, cols)]
print(f"Rectangular selection:\n{submatrix}")

Rectangular selection:
[[ 1  3]
 [ 9 11]]


In [17]:
# What np.ix_ does
row_idx, col_idx = np.ix_([0, 2], [1, 3])
print(f"Row indices shape: {row_idx.shape}")
print(f"Row indices:\n{row_idx}")
print(f"Col indices shape: {col_idx.shape}")
print(f"Col indices:\n{col_idx}")

Row indices shape: (2, 1)
Row indices:
[[0]
 [2]]
Col indices shape: (1, 2)
Col indices:
[[1 3]]


---
## 4. Combining Basic and Fancy Indexing

In [18]:
arr = np.arange(24).reshape(4, 6)
print(f"Array:\n{arr}")

Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [19]:
# Fancy rows, slice columns
result = arr[[0, 2], 1:4]
print(f"Rows [0,2], Cols 1:4:\n{result}")

Rows [0,2], Cols 1:4:
[[ 1  2  3]
 [13 14 15]]


In [20]:
# Slice rows, fancy columns
result = arr[1:3, [0, 2, 4]]
print(f"Rows 1:3, Cols [0,2,4]:\n{result}")

Rows 1:3, Cols [0,2,4]:
[[ 6  8 10]
 [12 14 16]]


In [21]:
# Single row (integer), fancy columns
result = arr[1, [0, 2, 4]]
print(f"Row 1, Cols [0,2,4]: {result}")

Row 1, Cols [0,2,4]: [ 6  8 10]


---
## 5. np.take and np.put

In [22]:
# np.take: alternative to fancy indexing
arr = np.array([10, 20, 30, 40, 50])

# Equivalent to arr[[0, 2, 4]]
result = np.take(arr, [0, 2, 4])
print(f"np.take: {result}")

np.take: [10 30 50]


In [23]:
# np.take along axis
arr = np.arange(12).reshape(3, 4)
print(f"Array:\n{arr}")

# Take columns 0 and 2
result = np.take(arr, [0, 2], axis=1)
print(f"Take cols [0,2]:\n{result}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Take cols [0,2]:
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [24]:
# np.put: modify array at indices
arr = np.arange(10)
print(f"Before: {arr}")

np.put(arr, [1, 3, 5], [100, 200, 300])
print(f"After put: {arr}")

Before: [0 1 2 3 4 5 6 7 8 9]
After put: [  0 100   2 200   4 300   6   7   8   9]


In [25]:
# Clip mode for out-of-bounds
arr = np.arange(5)
np.put(arr, [10], [999], mode='clip')  # 10 is out of bounds, clips to last
print(f"After put with clip: {arr}")

After put with clip: [  0   1   2   3 999]


---
## 6. np.take_along_axis and np.put_along_axis

In [26]:
# Useful for gathering values based on computed indices (like argsort)
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print(f"Array:\n{arr}")

Array:
[[3 1 4]
 [1 5 9]
 [2 6 5]]


In [27]:
# Get sorted indices per row
sort_idx = np.argsort(arr, axis=1)
print(f"Sort indices:\n{sort_idx}")

# Use take_along_axis to sort
sorted_arr = np.take_along_axis(arr, sort_idx, axis=1)
print(f"Sorted:\n{sorted_arr}")

Sort indices:
[[1 0 2]
 [0 1 2]
 [0 2 1]]
Sorted:
[[1 3 4]
 [1 5 9]
 [2 5 6]]


In [28]:
# Get top-k per row
k = 2
topk_idx = np.argsort(arr, axis=1)[:, -k:]
topk_values = np.take_along_axis(arr, topk_idx, axis=1)

print(f"Top-{k} indices:\n{topk_idx}")
print(f"Top-{k} values:\n{topk_values}")

Top-2 indices:
[[0 2]
 [1 2]
 [2 1]]
Top-2 values:
[[3 4]
 [5 9]
 [5 6]]


---
## 7. Advanced Selection Patterns

In [29]:
# Pattern: Select diagonal elements
arr = np.arange(16).reshape(4, 4)
print(f"Array:\n{arr}")

# Main diagonal
diag_idx = np.arange(4)
diagonal = arr[diag_idx, diag_idx]
print(f"Main diagonal: {diagonal}")

# Anti-diagonal
anti_diag = arr[diag_idx, diag_idx[::-1]]
print(f"Anti-diagonal: {anti_diag}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Main diagonal: [ 0  5 10 15]
Anti-diagonal: [ 3  6  9 12]


In [30]:
# Pattern: Select upper/lower triangle
# Using np.triu_indices, np.tril_indices
upper_idx = np.triu_indices(4, k=1)
print(f"Upper triangle elements: {arr[upper_idx]}")

lower_idx = np.tril_indices(4, k=-1)
print(f"Lower triangle elements: {arr[lower_idx]}")

Upper triangle elements: [ 1  2  3  6  7 11]
Lower triangle elements: [ 4  8  9 12 13 14]


In [31]:
# Pattern: Sample random elements
np.random.seed(42)
arr = np.arange(100)

# Random sample without replacement
indices = np.random.choice(len(arr), size=10, replace=False)
sample = arr[indices]
print(f"Random sample: {sample}")

Random sample: [83 53 70 45 44 39 22 80 10  0]


In [32]:
# Pattern: Gather from 2D based on 1D indices per row
# Like softmax sampling in ML
arr = np.arange(12).reshape(3, 4)
print(f"Array:\n{arr}")

# Select column index for each row
col_indices = np.array([1, 0, 3])

# Use advanced indexing
row_indices = np.arange(3)
selected = arr[row_indices, col_indices]
print(f"Selected: {selected}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Selected: [ 1  4 11]


---
## Key Points Summary

**Fancy Indexing Basics:**
- Use integer arrays/lists to select elements
- Can repeat and reorder indices
- Always returns COPY (not view)
- Assignment still modifies original

**Multi-dimensional:**
- `arr[[r1,r2], [c1,c2]]` selects pairs: (r1,c1), (r2,c2)
- `arr[np.ix_([r1,r2], [c1,c2])]` selects rectangle

**Useful Functions:**
- `np.take(arr, indices, axis)`: Fancy indexing
- `np.put(arr, indices, values)`: Assignment
- `np.take_along_axis()`: Use with argsort results
- `np.ix_()`: Create mesh for rectangular selection

---
## Interview Tips

**Q1: Does fancy indexing return a view or copy?**
> Always returns a COPY. Only basic slicing returns views. This is because fancy indexing can select non-contiguous elements.

**Q2: How do you select a rectangular submatrix with specific rows and columns?**
> Use `np.ix_`: `arr[np.ix_(rows, cols)]`. Direct `arr[rows, cols]` selects pairs, not rectangle.

**Q3: How do you select top-k elements per row?**
> `indices = np.argsort(arr, axis=1)[:, -k:]` then `np.take_along_axis(arr, indices, axis=1)`

**Q4: What happens if fancy index is out of bounds?**
> Raises IndexError. Use `np.take` with `mode='clip'` or `mode='wrap'` for safe handling.

---
## Practice Exercises

### Exercise 1: Shuffle rows of a 2D array

In [33]:
arr = np.arange(12).reshape(4, 3)
print(f"Original:\n{arr}")
# Shuffle the rows randomly


Original:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [34]:
# Solution
arr = np.arange(12).reshape(4, 3)
indices = np.random.permutation(len(arr))
shuffled = arr[indices]
print(f"Shuffled indices: {indices}")
print(f"Shuffled:\n{shuffled}")

Shuffled indices: [3 1 0 2]
Shuffled:
[[ 9 10 11]
 [ 3  4  5]
 [ 0  1  2]
 [ 6  7  8]]


### Exercise 2: Extract every other element in multiple positions

In [35]:
# From a 4x6 array, extract elements at (0,1), (1,3), (2,5), (3,1)
arr = np.arange(24).reshape(4, 6)
print(f"Array:\n{arr}")


Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [36]:
# Solution
arr = np.arange(24).reshape(4, 6)
rows = [0, 1, 2, 3]
cols = [1, 3, 5, 1]

selected = arr[rows, cols]
print(f"Selected elements: {selected}")

Selected elements: [ 1  9 17 19]


### Exercise 3: One-hot to label conversion

In [37]:
# Convert one-hot encoded matrix to label indices
one_hot = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 0]
])


In [38]:
# Solution
one_hot = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 0]
])

labels = np.argmax(one_hot, axis=1)
print(f"One-hot:\n{one_hot}")
print(f"Labels: {labels}")

One-hot:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]]
Labels: [0 1 2 1]


---
## Next Notebook
**02_boolean_indexing.ipynb** - Boolean masks, conditional selection, and logical operations.